
flyway.url=jdbc:oracle:thin:@//oracle:1521/FREEPDB1
flyway.user=ORDEVO
flyway.password=Ordevo_Dev_2026
flyway.schemas=ORDEVO
flyway.defaultSchema=ORDEVO
flyway.locations=filesystem:/flyway/sql
flyway.baselineOnMigrate=true
flyway.baselineVersion=0
flyway.validateMigrationNaming=true
