
ALTER SESSION SET CONTAINER = FREEPDB1;

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM dba_users WHERE username = 'ORDEVO';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE
      'CREATE USER ORDEVO IDENTIFIED BY "Ordevo_Dev_2026" ' ||
      'DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS';
    EXECUTE IMMEDIATE
      'GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, ' ||
      'CREATE PROCEDURE, CREATE TRIGGER, CREATE TYPE, CREATE MATERIALIZED VIEW, ' ||
      'CREATE JOB TO ORDEVO';
  END IF;
END;
/

EXIT;
