
CREATE TABLE CASH_REGISTERS (
  ID         VARCHAR2(36)  NOT NULL,
  TENANT_ID  VARCHAR2(36)  NOT NULL,
  BRANCH_ID  VARCHAR2(36)  NOT NULL,
  NAME       VARCHAR2(120) NOT NULL,
  IS_ACTIVE  NUMBER(1) DEFAULT 1 NOT NULL,
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_CASH_REGISTERS PRIMARY KEY (ID),
  CONSTRAINT FK_REG_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID),
  CONSTRAINT UQ_REG_NAME UNIQUE (BRANCH_ID, NAME),
  CONSTRAINT CK_REG_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);
CREATE INDEX IX_REG_TENANT ON CASH_REGISTERS (TENANT_ID, BRANCH_ID);

CREATE TABLE REGISTER_SESSIONS (
  ID               VARCHAR2(36)             NOT NULL,
  TENANT_ID        VARCHAR2(36)             NOT NULL,
  BRANCH_ID        VARCHAR2(36)             NOT NULL,
  REGISTER_ID      VARCHAR2(36)             NOT NULL,
  STATUS           VARCHAR2(16) DEFAULT 'open' NOT NULL,
  OPENING_AMOUNT   NUMBER(18,4) DEFAULT 0   NOT NULL,
  OPENED_BY        VARCHAR2(36),
  OPENED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CLOSING_COUNTED  NUMBER(18,4),
  CLOSING_EXPECTED NUMBER(18,4),
  DIFFERENCE       NUMBER(18,4),
  CLOSED_BY        VARCHAR2(36),
  CLOSED_AT        TIMESTAMP WITH TIME ZONE,
  NOTE             VARCHAR2(500),
  ROW_VERSION      NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_REGISTER_SESSIONS PRIMARY KEY (ID),
  CONSTRAINT FK_SESSION_REGISTER FOREIGN KEY (REGISTER_ID) REFERENCES CASH_REGISTERS (ID),
  CONSTRAINT CK_SESSION_STATUS CHECK (STATUS IN ('open','closed'))
);
CREATE INDEX IX_SESSION_REG ON REGISTER_SESSIONS (REGISTER_ID, STATUS);
CREATE INDEX IX_SESSION_TENANT ON REGISTER_SESSIONS (TENANT_ID, BRANCH_ID);
