
CREATE TABLE DAILY_SALES_ARCHIVE (
  ID            VARCHAR2(36) NOT NULL,
  TENANT_ID     VARCHAR2(36) NOT NULL,
  BRANCH_ID     VARCHAR2(36) NOT NULL,
  BUSINESS_DATE DATE         NOT NULL,
  TOTAL_ORDERS  NUMBER(12)   DEFAULT 0 NOT NULL,
  TOTAL_REVENUE NUMBER(18,4) DEFAULT 0 NOT NULL,
  TOTAL_ITEMS   NUMBER(14,3) DEFAULT 0 NOT NULL,
  ARCHIVED_BY   VARCHAR2(36),
  ARCHIVED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_DAILY_SALES_ARCHIVE PRIMARY KEY (ID),
  CONSTRAINT UQ_DAILY_ARCHIVE UNIQUE (TENANT_ID, BRANCH_ID, BUSINESS_DATE)
);

CREATE MATERIALIZED VIEW MV_DAILY_SALES
REFRESH COMPLETE ON DEMAND AS
SELECT o.TENANT_ID, o.BRANCH_ID, TRUNC(o.CLOSED_AT) AS BUSINESS_DATE,
       COUNT(*)              AS ORDER_COUNT,
       NVL(SUM(o.TOTAL),0)   AS REVENUE,
       NVL(SUM(o.TAX_TOTAL),0)      AS TAX_TOTAL,
       NVL(SUM(o.DISCOUNT_TOTAL),0) AS DISCOUNT_TOTAL
FROM ORDERS o
WHERE o.STATUS = 'closed' AND o.CLOSED_AT IS NOT NULL
GROUP BY o.TENANT_ID, o.BRANCH_ID, TRUNC(o.CLOSED_AT);

CREATE OR REPLACE PACKAGE PKG_REPORTING AS
  PROCEDURE ARCHIVE_DAILY(p_tenant_id IN VARCHAR2, p_branch_id IN VARCHAR2, p_business_date IN DATE, p_user_id IN VARCHAR2);
  FUNCTION  DAILY_STATS_JSON(p_tenant_id IN VARCHAR2, p_branch_id IN VARCHAR2, p_business_date IN DATE) RETURN CLOB;
  PROCEDURE REFRESH_MV;
END PKG_REPORTING;
/

CREATE OR REPLACE PACKAGE BODY PKG_REPORTING AS

  PROCEDURE ARCHIVE_DAILY(p_tenant_id IN VARCHAR2, p_branch_id IN VARCHAR2, p_business_date IN DATE, p_user_id IN VARCHAR2) IS
  BEGIN
    MERGE INTO DAILY_SALES_ARCHIVE d
    USING (
      SELECT COUNT(DISTINCT o.ID)          AS OC,
             NVL(SUM(oi.LINE_TOTAL),0)      AS REV,
             NVL(SUM(oi.QUANTITY),0)        AS ITEMS
      FROM ORDERS o
      LEFT JOIN ORDER_ITEMS oi ON oi.ORDER_ID = o.ID AND oi.STATUS <> 'void' AND oi.IS_COMP = 0
      WHERE o.TENANT_ID = p_tenant_id AND o.BRANCH_ID = p_branch_id
        AND o.STATUS = 'closed' AND TRUNC(o.CLOSED_AT) = p_business_date
    ) s
    ON (d.TENANT_ID = p_tenant_id AND d.BRANCH_ID = p_branch_id AND d.BUSINESS_DATE = p_business_date)
    WHEN MATCHED THEN UPDATE SET
      d.TOTAL_ORDERS = s.OC, d.TOTAL_REVENUE = s.REV, d.TOTAL_ITEMS = s.ITEMS,
      d.ARCHIVED_BY = p_user_id, d.ARCHIVED_AT = SYSTIMESTAMP
    WHEN NOT MATCHED THEN INSERT (ID, TENANT_ID, BRANCH_ID, BUSINESS_DATE, TOTAL_ORDERS, TOTAL_REVENUE, TOTAL_ITEMS, ARCHIVED_BY)
      VALUES (PKG_ORDERING.NEW_ID, p_tenant_id, p_branch_id, p_business_date, s.OC, s.REV, s.ITEMS, p_user_id);
  END ARCHIVE_DAILY;

  FUNCTION DAILY_STATS_JSON(p_tenant_id IN VARCHAR2, p_branch_id IN VARCHAR2, p_business_date IN DATE) RETURN CLOB IS
    v_json CLOB;
  BEGIN
    SELECT JSON_OBJECT(
             'date'        VALUE TO_CHAR(p_business_date, 'YYYY-MM-DD'),
             'orderCount'  VALUE COUNT(DISTINCT o.ID),
             'revenue'     VALUE NVL(SUM(oi.LINE_TOTAL),0),
             'itemCount'   VALUE NVL(SUM(oi.QUANTITY),0)
             RETURNING CLOB)
      INTO v_json
      FROM ORDERS o
      LEFT JOIN ORDER_ITEMS oi ON oi.ORDER_ID = o.ID AND oi.STATUS <> 'void' AND oi.IS_COMP = 0
     WHERE o.TENANT_ID = p_tenant_id AND o.BRANCH_ID = p_branch_id
       AND o.STATUS = 'closed' AND TRUNC(o.CLOSED_AT) = p_business_date;
    RETURN v_json;
  END DAILY_STATS_JSON;

  PROCEDURE REFRESH_MV IS
  BEGIN
    DBMS_MVIEW.REFRESH('MV_DAILY_SALES', 'C');
  END REFRESH_MV;

END PKG_REPORTING;
/
