
CREATE SEQUENCE CRM_RESERVATION_NO_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;

CREATE TABLE CRM_CUSTOMERS (
  ID              VARCHAR2(36)             NOT NULL,
  TENANT_ID       VARCHAR2(36)             NOT NULL,
  PHONE           VARCHAR2(40)             NOT NULL,
  FULL_NAME       VARCHAR2(200),
  EMAIL           VARCHAR2(160),
  BIRTHDAY        DATE,
  NOTES           CLOB,
  PREFERENCES     CLOB,
  LOYALTY_TIER    VARCHAR2(20) DEFAULT 'bronze' NOT NULL,
  LOYALTY_POINTS  NUMBER(12)  DEFAULT 0    NOT NULL,
  TOTAL_SPENT     NUMBER(18,4) DEFAULT 0   NOT NULL,
  VISIT_COUNT     NUMBER(10) DEFAULT 0     NOT NULL,
  SMS_CONSENT     NUMBER(1) DEFAULT 1      NOT NULL,
  EMAIL_CONSENT   NUMBER(1) DEFAULT 1      NOT NULL,
  IS_BLOCKED      NUMBER(1) DEFAULT 0      NOT NULL,
  BLOCK_REASON    VARCHAR2(500),
  CREATED_BY      VARCHAR2(36),
  UPDATED_BY      VARCHAR2(36),
  CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  ROW_VERSION     NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_CRM_CUSTOMERS PRIMARY KEY (ID),
  CONSTRAINT FK_CRM_CUSTOMERS_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT UQ_CRM_CUSTOMERS_PHONE UNIQUE (TENANT_ID, PHONE),
  CONSTRAINT CK_CRM_CUSTOMERS_TIER CHECK (LOYALTY_TIER IN ('bronze','silver','gold','platinum')),
  CONSTRAINT CK_CRM_CUSTOMERS_SMS CHECK (SMS_CONSENT IN (0,1)),
  CONSTRAINT CK_CRM_CUSTOMERS_EMAIL CHECK (EMAIL_CONSENT IN (0,1)),
  CONSTRAINT CK_CRM_CUSTOMERS_BLOCKED CHECK (IS_BLOCKED IN (0,1)),
  CONSTRAINT CK_CRM_CUSTOMERS_PREFS CHECK (PREFERENCES IS NULL OR PREFERENCES IS JSON)
);
CREATE INDEX IX_CRM_CUSTOMERS_TENANT ON CRM_CUSTOMERS (TENANT_ID, UPDATED_AT DESC);
CREATE INDEX IX_CRM_CUSTOMERS_EMAIL ON CRM_CUSTOMERS (TENANT_ID, EMAIL);

CREATE TABLE CRM_CUSTOMER_ADDRESSES (
  ID              VARCHAR2(36)             NOT NULL,
  TENANT_ID       VARCHAR2(36)             NOT NULL,
  CUSTOMER_ID     VARCHAR2(36)             NOT NULL,
  LABEL           VARCHAR2(80)             NOT NULL,
  ADDRESS_LINE1   VARCHAR2(240)            NOT NULL,
  ADDRESS_LINE2   VARCHAR2(240),
  DISTRICT        VARCHAR2(100),
  CITY            VARCHAR2(100),
  POSTAL_CODE     VARCHAR2(20),
  LATITUDE        NUMBER(10,7),
  LONGITUDE       NUMBER(10,7),
  DELIVERY_NOTE   VARCHAR2(500),
  IS_DEFAULT      NUMBER(1) DEFAULT 0      NOT NULL,
  CREATED_BY      VARCHAR2(36),
  UPDATED_BY      VARCHAR2(36),
  CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  ROW_VERSION     NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_CRM_CUSTOMER_ADDR PRIMARY KEY (ID),
  CONSTRAINT FK_CRM_ADDR_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT FK_CRM_ADDR_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CRM_CUSTOMERS (ID) ON DELETE CASCADE,
  CONSTRAINT CK_CRM_ADDR_DEFAULT CHECK (IS_DEFAULT IN (0,1))
);
CREATE INDEX IX_CRM_ADDR_CUSTOMER ON CRM_CUSTOMER_ADDRESSES (TENANT_ID, CUSTOMER_ID);

CREATE TABLE CRM_LOYALTY_TRANSACTIONS (
  ID               VARCHAR2(36)            NOT NULL,
  TENANT_ID        VARCHAR2(36)            NOT NULL,
  CUSTOMER_ID      VARCHAR2(36)            NOT NULL,
  TRANSACTION_TYPE VARCHAR2(20)            NOT NULL,
  POINTS           NUMBER(12)              NOT NULL,
  BALANCE_AFTER    NUMBER(12)              NOT NULL,
  ORDER_ID         VARCHAR2(36),
  REASON           VARCHAR2(500),
  CREATED_BY       VARCHAR2(36),
  CREATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_CRM_LOYALTY_TX PRIMARY KEY (ID),
  CONSTRAINT FK_CRM_LOYALTY_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT FK_CRM_LOYALTY_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CRM_CUSTOMERS (ID) ON DELETE CASCADE,
  CONSTRAINT FK_CRM_LOYALTY_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID) ON DELETE SET NULL,
  CONSTRAINT CK_CRM_LOYALTY_TYPE CHECK (TRANSACTION_TYPE IN ('earn','redeem','adjust','expire'))
);
CREATE INDEX IX_CRM_LOYALTY_CUSTOMER ON CRM_LOYALTY_TRANSACTIONS (TENANT_ID, CUSTOMER_ID, CREATED_AT DESC);

CREATE TABLE CRM_CAMPAIGNS (
  ID                       VARCHAR2(36)             NOT NULL,
  TENANT_ID                VARCHAR2(36)             NOT NULL,
  BRANCH_ID                VARCHAR2(36),
  CODE                     VARCHAR2(40)             NOT NULL,
  NAME                     VARCHAR2(200)            NOT NULL,
  DESCRIPTION              CLOB,
  DISCOUNT_TYPE            VARCHAR2(20)             NOT NULL,
  DISCOUNT_VALUE           NUMBER(18,4)             NOT NULL,
  MAX_DISCOUNT_AMOUNT      NUMBER(18,4),
  MIN_ORDER_AMOUNT         NUMBER(18,4),
  USAGE_LIMIT_PER_CUSTOMER NUMBER(6),
  TOTAL_USAGE_LIMIT        NUMBER(10),
  USAGE_COUNT              NUMBER(10) DEFAULT 0     NOT NULL,
  STARTS_AT                TIMESTAMP WITH TIME ZONE NOT NULL,
  ENDS_AT                  TIMESTAMP WITH TIME ZONE,
  IS_ACTIVE                NUMBER(1) DEFAULT 1      NOT NULL,
  AUTO_APPLY               NUMBER(1) DEFAULT 0      NOT NULL,
  PRIORITY                 NUMBER(3) DEFAULT 10     NOT NULL,
  CREATED_BY               VARCHAR2(36),
  UPDATED_BY               VARCHAR2(36),
  CREATED_AT               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  ROW_VERSION              NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_CRM_CAMPAIGNS PRIMARY KEY (ID),
  CONSTRAINT FK_CRM_CAMPAIGN_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT FK_CRM_CAMPAIGN_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID),
  CONSTRAINT UQ_CRM_CAMPAIGN_CODE UNIQUE (TENANT_ID, CODE),
  CONSTRAINT CK_CRM_CAMPAIGN_DISC CHECK (DISCOUNT_TYPE IN ('percent','amount')),
  CONSTRAINT CK_CRM_CAMPAIGN_ACTIVE CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_CRM_CAMPAIGN_AUTO CHECK (AUTO_APPLY IN (0,1)),
  CONSTRAINT CK_CRM_CAMPAIGN_VALUE CHECK (DISCOUNT_VALUE > 0)
);
CREATE INDEX IX_CRM_CAMPAIGN_ACTIVE ON CRM_CAMPAIGNS (TENANT_ID, IS_ACTIVE, STARTS_AT, ENDS_AT);

CREATE TABLE CRM_CAMPAIGN_USAGE (
  ID              VARCHAR2(36)             NOT NULL,
  TENANT_ID       VARCHAR2(36)             NOT NULL,
  CAMPAIGN_ID     VARCHAR2(36)             NOT NULL,
  CUSTOMER_ID     VARCHAR2(36),
  ORDER_ID        VARCHAR2(36)             NOT NULL,
  DISCOUNT_AMOUNT NUMBER(18,4)             NOT NULL,
  CREATED_BY      VARCHAR2(36),
  USED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_CRM_CAMPAIGN_USAGE PRIMARY KEY (ID),
  CONSTRAINT FK_CRM_USAGE_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT FK_CRM_USAGE_CAMPAIGN FOREIGN KEY (CAMPAIGN_ID) REFERENCES CRM_CAMPAIGNS (ID) ON DELETE CASCADE,
  CONSTRAINT FK_CRM_USAGE_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CRM_CUSTOMERS (ID) ON DELETE SET NULL,
  CONSTRAINT FK_CRM_USAGE_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID) ON DELETE CASCADE,
  CONSTRAINT UQ_CRM_USAGE_ORDER_CAMPAIGN UNIQUE (CAMPAIGN_ID, ORDER_ID)
);
CREATE INDEX IX_CRM_USAGE_CUSTOMER ON CRM_CAMPAIGN_USAGE (TENANT_ID, CUSTOMER_ID, USED_AT DESC);

CREATE TABLE CRM_RESERVATIONS (
  ID               VARCHAR2(36)             NOT NULL,
  TENANT_ID        VARCHAR2(36)             NOT NULL,
  BRANCH_ID        VARCHAR2(36)             NOT NULL,
  RESERVATION_NO   NUMBER(12)               NOT NULL,
  CUSTOMER_ID      VARCHAR2(36),
  CUSTOMER_NAME    VARCHAR2(200)            NOT NULL,
  CUSTOMER_PHONE   VARCHAR2(40)             NOT NULL,
  RESERVATION_DATE DATE                     NOT NULL,
  RESERVATION_TIME VARCHAR2(5)              NOT NULL,
  GUEST_COUNT      NUMBER(4)                NOT NULL,
  TABLE_ID         VARCHAR2(36),
  NOTES            CLOB,
  STATUS           VARCHAR2(20) DEFAULT 'pending' NOT NULL,
  CONFIRMED_AT     TIMESTAMP WITH TIME ZONE,
  SEATED_AT        TIMESTAMP WITH TIME ZONE,
  CANCELLED_AT     TIMESTAMP WITH TIME ZONE,
  CANCEL_REASON    VARCHAR2(500),
  CREATED_BY       VARCHAR2(36),
  UPDATED_BY       VARCHAR2(36),
  CREATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  ROW_VERSION      NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_CRM_RESERVATIONS PRIMARY KEY (ID),
  CONSTRAINT FK_CRM_RESV_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT FK_CRM_RESV_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID),
  CONSTRAINT FK_CRM_RESV_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CRM_CUSTOMERS (ID) ON DELETE SET NULL,
  CONSTRAINT FK_CRM_RESV_TABLE FOREIGN KEY (TABLE_ID) REFERENCES DINING_TABLES (ID) ON DELETE SET NULL,
  CONSTRAINT UQ_CRM_RESV_NO UNIQUE (TENANT_ID, BRANCH_ID, RESERVATION_NO),
  CONSTRAINT CK_CRM_RESV_STATUS CHECK (STATUS IN ('pending','confirmed','seated','cancelled','no_show')),
  CONSTRAINT CK_CRM_RESV_GUESTS CHECK (GUEST_COUNT > 0),
  CONSTRAINT CK_CRM_RESV_TIME CHECK (REGEXP_LIKE(RESERVATION_TIME, '^[0-2][0-9]:[0-5][0-9]$'))
);
CREATE INDEX IX_CRM_RESV_BRANCH_DATE ON CRM_RESERVATIONS (TENANT_ID, BRANCH_ID, RESERVATION_DATE, STATUS);

CREATE TABLE CRM_DELIVERY_ZONES (
  ID                 VARCHAR2(36)             NOT NULL,
  TENANT_ID          VARCHAR2(36)             NOT NULL,
  BRANCH_ID          VARCHAR2(36)             NOT NULL,
  NAME               VARCHAR2(160)            NOT NULL,
  CENTER_LAT         NUMBER(10,7)             NOT NULL,
  CENTER_LNG         NUMBER(10,7)             NOT NULL,
  RADIUS_KM          NUMBER(9,3)              NOT NULL,
  DELIVERY_FEE       NUMBER(18,4) DEFAULT 0   NOT NULL,
  MIN_ORDER_AMOUNT   NUMBER(18,4) DEFAULT 0   NOT NULL,
  FREE_DELIVERY_OVER NUMBER(18,4),
  ESTIMATED_MINUTES  NUMBER(5)                NOT NULL,
  IS_ACTIVE          NUMBER(1) DEFAULT 1      NOT NULL,
  CREATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  ROW_VERSION        NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_CRM_DELIVERY_ZONES PRIMARY KEY (ID),
  CONSTRAINT FK_CRM_ZONE_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT FK_CRM_ZONE_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID),
  CONSTRAINT CK_CRM_ZONE_ACTIVE CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_CRM_ZONE_RADIUS CHECK (RADIUS_KM > 0)
);
CREATE INDEX IX_CRM_ZONE_BRANCH ON CRM_DELIVERY_ZONES (TENANT_ID, BRANCH_ID, IS_ACTIVE);

CREATE TABLE CRM_COURIERS (
  ID               VARCHAR2(36)             NOT NULL,
  TENANT_ID        VARCHAR2(36)             NOT NULL,
  BRANCH_ID        VARCHAR2(36)             NOT NULL,
  USER_ID          VARCHAR2(36),
  FULL_NAME        VARCHAR2(200)            NOT NULL,
  PHONE            VARCHAR2(40)             NOT NULL,
  LICENSE_PLATE    VARCHAR2(20),
  VEHICLE_TYPE     VARCHAR2(20) DEFAULT 'motorbike' NOT NULL,
  STATUS           VARCHAR2(20) DEFAULT 'off_duty' NOT NULL,
  CURRENT_ORDER_ID VARCHAR2(36),
  LAST_LAT         NUMBER(10,7),
  LAST_LNG         NUMBER(10,7),
  LAST_LOCATION_AT TIMESTAMP WITH TIME ZONE,
  TOTAL_DELIVERIES NUMBER(10) DEFAULT 0     NOT NULL,
  RATING           NUMBER(3,2),
  IS_ACTIVE        NUMBER(1) DEFAULT 1      NOT NULL,
  CREATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  ROW_VERSION      NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_CRM_COURIERS PRIMARY KEY (ID),
  CONSTRAINT FK_CRM_COURIER_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT FK_CRM_COURIER_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID),
  CONSTRAINT FK_CRM_COURIER_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE SET NULL,
  CONSTRAINT FK_CRM_COURIER_ORDER FOREIGN KEY (CURRENT_ORDER_ID) REFERENCES ORDERS (ID) ON DELETE SET NULL,
  CONSTRAINT UQ_CRM_COURIER_PHONE UNIQUE (TENANT_ID, PHONE),
  CONSTRAINT CK_CRM_COURIER_VEHICLE CHECK (VEHICLE_TYPE IN ('bike','motorbike','car','walk')),
  CONSTRAINT CK_CRM_COURIER_STATUS CHECK (STATUS IN ('off_duty','available','on_delivery')),
  CONSTRAINT CK_CRM_COURIER_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);
CREATE INDEX IX_CRM_COURIER_BRANCH ON CRM_COURIERS (TENANT_ID, BRANCH_ID, STATUS, IS_ACTIVE);

CREATE TABLE CRM_DELIVERIES (
  ID                VARCHAR2(36)             NOT NULL,
  TENANT_ID         VARCHAR2(36)             NOT NULL,
  BRANCH_ID         VARCHAR2(36)             NOT NULL,
  ORDER_ID          VARCHAR2(36)             NOT NULL,
  CUSTOMER_ID       VARCHAR2(36),
  COURIER_ID        VARCHAR2(36),
  DELIVERY_ZONE_ID  VARCHAR2(36),
  DELIVERY_ADDRESS  VARCHAR2(1000)           NOT NULL,
  DELIVERY_LAT      NUMBER(10,7),
  DELIVERY_LNG      NUMBER(10,7),
  DELIVERY_FEE      NUMBER(18,4) DEFAULT 0   NOT NULL,
  ESTIMATED_MINUTES NUMBER(5)                NOT NULL,
  STATUS            VARCHAR2(20) DEFAULT 'pending' NOT NULL,
  ASSIGNED_AT       TIMESTAMP WITH TIME ZONE,
  PICKED_UP_AT      TIMESTAMP WITH TIME ZONE,
  DELIVERED_AT      TIMESTAMP WITH TIME ZONE,
  RATING            NUMBER(1),
  FEEDBACK          CLOB,
  CREATED_BY        VARCHAR2(36),
  UPDATED_BY        VARCHAR2(36),
  CREATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  ROW_VERSION       NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_CRM_DELIVERIES PRIMARY KEY (ID),
  CONSTRAINT FK_CRM_DELIVERY_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT FK_CRM_DELIVERY_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID),
  CONSTRAINT FK_CRM_DELIVERY_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID) ON DELETE CASCADE,
  CONSTRAINT FK_CRM_DELIVERY_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CRM_CUSTOMERS (ID) ON DELETE SET NULL,
  CONSTRAINT FK_CRM_DELIVERY_COURIER FOREIGN KEY (COURIER_ID) REFERENCES CRM_COURIERS (ID) ON DELETE SET NULL,
  CONSTRAINT FK_CRM_DELIVERY_ZONE FOREIGN KEY (DELIVERY_ZONE_ID) REFERENCES CRM_DELIVERY_ZONES (ID) ON DELETE SET NULL,
  CONSTRAINT UQ_CRM_DELIVERY_ORDER UNIQUE (ORDER_ID),
  CONSTRAINT CK_CRM_DELIVERY_STATUS CHECK (STATUS IN ('pending','assigned','picked_up','on_way','delivered','cancelled')),
  CONSTRAINT CK_CRM_DELIVERY_RATING CHECK (RATING IS NULL OR RATING BETWEEN 1 AND 5)
);
CREATE INDEX IX_CRM_DELIVERY_ACTIVE ON CRM_DELIVERIES (TENANT_ID, BRANCH_ID, STATUS, CREATED_AT);
CREATE INDEX IX_CRM_DELIVERY_COURIER ON CRM_DELIVERIES (TENANT_ID, COURIER_ID, STATUS);

ALTER TABLE ORDERS ADD (
  CUSTOMER_ID VARCHAR2(36),
  CONSTRAINT FK_ORDERS_CRM_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CRM_CUSTOMERS (ID) ON DELETE SET NULL
);
CREATE INDEX IX_ORDERS_CUSTOMER ON ORDERS (TENANT_ID, CUSTOMER_ID);
