
CREATE SEQUENCE SYNC_CHANGE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE SYNC_ENTITY_CONFIG (
  ENTITY_NAME       VARCHAR2(80)             NOT NULL,
  TABLE_NAME        VARCHAR2(80)             NOT NULL,
  IS_BRANCH_SCOPED  NUMBER(1) DEFAULT 1      NOT NULL,
  ALLOW_CLIENT_PUSH NUMBER(1) DEFAULT 0      NOT NULL,
  IS_ACTIVE         NUMBER(1) DEFAULT 1      NOT NULL,
  SORT_ORDER        NUMBER(6) DEFAULT 0      NOT NULL,
  CREATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_SYNC_ENTITY_CONFIG PRIMARY KEY (ENTITY_NAME),
  CONSTRAINT UQ_SYNC_ENTITY_TABLE UNIQUE (TABLE_NAME),
  CONSTRAINT CK_SYNC_ENTITY_BRANCH CHECK (IS_BRANCH_SCOPED IN (0,1)),
  CONSTRAINT CK_SYNC_ENTITY_PUSH CHECK (ALLOW_CLIENT_PUSH IN (0,1)),
  CONSTRAINT CK_SYNC_ENTITY_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);

CREATE TABLE SYNC_OUTBOX (
  CHANGE_VERSION   NUMBER(19)               NOT NULL,
  ID               VARCHAR2(36)             NOT NULL,
  TENANT_ID        VARCHAR2(36)             NOT NULL,
  BRANCH_ID        VARCHAR2(36),
  ENTITY_NAME      VARCHAR2(80)             NOT NULL,
  ENTITY_ID        VARCHAR2(100)            NOT NULL,
  OPERATION        VARCHAR2(20)             NOT NULL,
  ROW_VERSION      NUMBER(19),
  PAYLOAD          CLOB,
  ORIGIN_DEVICE_ID VARCHAR2(36),
  ORIGIN_USER_ID   VARCHAR2(36),
  OCCURRED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  RETENTION_UNTIL  TIMESTAMP WITH TIME ZONE,
  CONSTRAINT PK_SYNC_OUTBOX PRIMARY KEY (CHANGE_VERSION),
  CONSTRAINT UQ_SYNC_OUTBOX_ID UNIQUE (ID),
  CONSTRAINT FK_SYNC_OUTBOX_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT FK_SYNC_OUTBOX_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID),
  CONSTRAINT FK_SYNC_OUTBOX_ENTITY FOREIGN KEY (ENTITY_NAME) REFERENCES SYNC_ENTITY_CONFIG (ENTITY_NAME),
  CONSTRAINT FK_SYNC_OUTBOX_DEVICE FOREIGN KEY (ORIGIN_DEVICE_ID) REFERENCES DEVICES (ID) ON DELETE SET NULL,
  CONSTRAINT CK_SYNC_OUTBOX_OP CHECK (OPERATION IN ('upsert','delete','snapshot','custom')),
  CONSTRAINT CK_SYNC_OUTBOX_JSON CHECK (PAYLOAD IS NULL OR PAYLOAD IS JSON)
);
CREATE INDEX IX_SYNC_OUTBOX_TENANT_VERSION ON SYNC_OUTBOX (TENANT_ID, CHANGE_VERSION);
CREATE INDEX IX_SYNC_OUTBOX_BRANCH_VERSION ON SYNC_OUTBOX (TENANT_ID, BRANCH_ID, CHANGE_VERSION);
CREATE INDEX IX_SYNC_OUTBOX_ENTITY ON SYNC_OUTBOX (TENANT_ID, ENTITY_NAME, ENTITY_ID);

CREATE TABLE SYNC_DEVICE_CHECKPOINTS (
  TENANT_ID          VARCHAR2(36)             NOT NULL,
  DEVICE_ID          VARCHAR2(36)             NOT NULL,
  BRANCH_ID          VARCHAR2(36),
  LAST_PULL_VERSION  NUMBER(19) DEFAULT 0     NOT NULL,
  LAST_PULL_AT       TIMESTAMP WITH TIME ZONE,
  LAST_PUSH_AT       TIMESTAMP WITH TIME ZONE,
  APP_VERSION        VARCHAR2(80),
  LOCAL_STORE_ID     VARCHAR2(80),
  CREATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_SYNC_DEVICE_CKPT PRIMARY KEY (TENANT_ID, DEVICE_ID),
  CONSTRAINT FK_SYNC_CKPT_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT FK_SYNC_CKPT_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES DEVICES (ID) ON DELETE CASCADE,
  CONSTRAINT FK_SYNC_CKPT_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID)
);

CREATE TABLE SYNC_CLIENT_MUTATIONS (
  ID                    VARCHAR2(36)             NOT NULL,
  TENANT_ID             VARCHAR2(36)             NOT NULL,
  BRANCH_ID             VARCHAR2(36),
  DEVICE_ID             VARCHAR2(36)             NOT NULL,
  CLIENT_MUTATION_ID    VARCHAR2(100)            NOT NULL,
  ENTITY_NAME           VARCHAR2(80)             NOT NULL,
  ENTITY_ID             VARCHAR2(100)            NOT NULL,
  OPERATION             VARCHAR2(20)             NOT NULL,
  BASE_CHANGE_VERSION   NUMBER(19),
  EXPECTED_ROW_VERSION  NUMBER(19),
  PAYLOAD               CLOB,
  STATUS                VARCHAR2(20) DEFAULT 'pending' NOT NULL,
  ERROR_CODE            VARCHAR2(100),
  ERROR_MESSAGE         VARCHAR2(1000),
  CREATED_BY            VARCHAR2(36),
  CREATED_AT            TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  APPLIED_AT            TIMESTAMP WITH TIME ZONE,
  CONSTRAINT PK_SYNC_CLIENT_MUTATIONS PRIMARY KEY (ID),
  CONSTRAINT FK_SYNC_MUT_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT FK_SYNC_MUT_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID),
  CONSTRAINT FK_SYNC_MUT_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES DEVICES (ID) ON DELETE CASCADE,
  CONSTRAINT FK_SYNC_MUT_ENTITY FOREIGN KEY (ENTITY_NAME) REFERENCES SYNC_ENTITY_CONFIG (ENTITY_NAME),
  CONSTRAINT UQ_SYNC_MUT_CLIENT UNIQUE (TENANT_ID, DEVICE_ID, CLIENT_MUTATION_ID),
  CONSTRAINT CK_SYNC_MUT_OP CHECK (OPERATION IN ('upsert','delete','custom')),
  CONSTRAINT CK_SYNC_MUT_STATUS CHECK (STATUS IN ('pending','applied','conflict','rejected')),
  CONSTRAINT CK_SYNC_MUT_JSON CHECK (PAYLOAD IS NULL OR PAYLOAD IS JSON)
);
CREATE INDEX IX_SYNC_MUT_PENDING ON SYNC_CLIENT_MUTATIONS (TENANT_ID, STATUS, CREATED_AT);
CREATE INDEX IX_SYNC_MUT_ENTITY ON SYNC_CLIENT_MUTATIONS (TENANT_ID, ENTITY_NAME, ENTITY_ID);

CREATE TABLE SYNC_CONFLICTS (
  ID                    VARCHAR2(36)             NOT NULL,
  TENANT_ID             VARCHAR2(36)             NOT NULL,
  BRANCH_ID             VARCHAR2(36),
  DEVICE_ID             VARCHAR2(36)             NOT NULL,
  MUTATION_ID           VARCHAR2(36)             NOT NULL,
  ENTITY_NAME           VARCHAR2(80)             NOT NULL,
  ENTITY_ID             VARCHAR2(100)            NOT NULL,
  SERVER_CHANGE_VERSION NUMBER(19),
  CLIENT_PAYLOAD        CLOB,
  SERVER_PAYLOAD        CLOB,
  RESOLUTION_STATUS     VARCHAR2(20) DEFAULT 'open' NOT NULL,
  RESOLUTION_NOTE       VARCHAR2(1000),
  CREATED_AT            TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  RESOLVED_AT           TIMESTAMP WITH TIME ZONE,
  RESOLVED_BY           VARCHAR2(36),
  CONSTRAINT PK_SYNC_CONFLICTS PRIMARY KEY (ID),
  CONSTRAINT FK_SYNC_CONFLICT_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT FK_SYNC_CONFLICT_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID),
  CONSTRAINT FK_SYNC_CONFLICT_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES DEVICES (ID) ON DELETE CASCADE,
  CONSTRAINT FK_SYNC_CONFLICT_MUT FOREIGN KEY (MUTATION_ID) REFERENCES SYNC_CLIENT_MUTATIONS (ID) ON DELETE CASCADE,
  CONSTRAINT CK_SYNC_CONFLICT_STATUS CHECK (RESOLUTION_STATUS IN ('open','server_wins','client_wins','manual')),
  CONSTRAINT CK_SYNC_CONFLICT_CLIENT_JSON CHECK (CLIENT_PAYLOAD IS NULL OR CLIENT_PAYLOAD IS JSON),
  CONSTRAINT CK_SYNC_CONFLICT_SERVER_JSON CHECK (SERVER_PAYLOAD IS NULL OR SERVER_PAYLOAD IS JSON)
);
CREATE INDEX IX_SYNC_CONFLICT_OPEN ON SYNC_CONFLICTS (TENANT_ID, RESOLUTION_STATUS, CREATED_AT);

INSERT INTO SYNC_ENTITY_CONFIG (ENTITY_NAME, TABLE_NAME, IS_BRANCH_SCOPED, ALLOW_CLIENT_PUSH, SORT_ORDER) VALUES ('menu.categories', 'MENU_CATEGORIES', 0, 0, 10);
INSERT INTO SYNC_ENTITY_CONFIG (ENTITY_NAME, TABLE_NAME, IS_BRANCH_SCOPED, ALLOW_CLIENT_PUSH, SORT_ORDER) VALUES ('menu.items', 'MENU_ITEMS', 0, 0, 20);
INSERT INTO SYNC_ENTITY_CONFIG (ENTITY_NAME, TABLE_NAME, IS_BRANCH_SCOPED, ALLOW_CLIENT_PUSH, SORT_ORDER) VALUES ('ordering.sections', 'TABLE_SECTIONS', 1, 1, 30);
INSERT INTO SYNC_ENTITY_CONFIG (ENTITY_NAME, TABLE_NAME, IS_BRANCH_SCOPED, ALLOW_CLIENT_PUSH, SORT_ORDER) VALUES ('ordering.tables', 'DINING_TABLES', 1, 1, 40);
INSERT INTO SYNC_ENTITY_CONFIG (ENTITY_NAME, TABLE_NAME, IS_BRANCH_SCOPED, ALLOW_CLIENT_PUSH, SORT_ORDER) VALUES ('ordering.orders', 'ORDERS', 1, 1, 50);
INSERT INTO SYNC_ENTITY_CONFIG (ENTITY_NAME, TABLE_NAME, IS_BRANCH_SCOPED, ALLOW_CLIENT_PUSH, SORT_ORDER) VALUES ('ordering.items', 'ORDER_ITEMS', 1, 1, 60);
INSERT INTO SYNC_ENTITY_CONFIG (ENTITY_NAME, TABLE_NAME, IS_BRANCH_SCOPED, ALLOW_CLIENT_PUSH, SORT_ORDER) VALUES ('payments.payments', 'PAYMENTS', 1, 0, 70);
INSERT INTO SYNC_ENTITY_CONFIG (ENTITY_NAME, TABLE_NAME, IS_BRANCH_SCOPED, ALLOW_CLIENT_PUSH, SORT_ORDER) VALUES ('kitchen.stations', 'KDS_STATIONS', 1, 0, 80);
INSERT INTO SYNC_ENTITY_CONFIG (ENTITY_NAME, TABLE_NAME, IS_BRANCH_SCOPED, ALLOW_CLIENT_PUSH, SORT_ORDER) VALUES ('inventory.stock_items', 'STOCK_ITEMS', 1, 0, 90);
INSERT INTO SYNC_ENTITY_CONFIG (ENTITY_NAME, TABLE_NAME, IS_BRANCH_SCOPED, ALLOW_CLIENT_PUSH, SORT_ORDER) VALUES ('crm.customers', 'CRM_CUSTOMERS', 0, 1, 100);
INSERT INTO SYNC_ENTITY_CONFIG (ENTITY_NAME, TABLE_NAME, IS_BRANCH_SCOPED, ALLOW_CLIENT_PUSH, SORT_ORDER) VALUES ('crm.reservations', 'CRM_RESERVATIONS', 1, 1, 110);
INSERT INTO SYNC_ENTITY_CONFIG (ENTITY_NAME, TABLE_NAME, IS_BRANCH_SCOPED, ALLOW_CLIENT_PUSH, SORT_ORDER) VALUES ('crm.deliveries', 'CRM_DELIVERIES', 1, 1, 120);
