
CREATE TABLE INTEGRATION_CONNECTORS (
  ID              VARCHAR2(36)             NOT NULL,
  TENANT_ID       VARCHAR2(36)             NOT NULL,
  BRANCH_ID       VARCHAR2(36),
  CODE            VARCHAR2(80)             NOT NULL,
  NAME            VARCHAR2(200)            NOT NULL,
  CONNECTOR_TYPE  VARCHAR2(40)             NOT NULL,
  PROVIDER_CODE   VARCHAR2(80)             NOT NULL,
  BASE_URL        VARCHAR2(1000),
  AUTH_TYPE       VARCHAR2(30) DEFAULT 'none' NOT NULL,
  SECRET_REF      VARCHAR2(300),
  SETTINGS        CLOB,
  STATUS          VARCHAR2(20) DEFAULT 'draft' NOT NULL,
  IS_ACTIVE       NUMBER(1) DEFAULT 1      NOT NULL,
  LAST_SUCCESS_AT TIMESTAMP WITH TIME ZONE,
  LAST_FAILURE_AT TIMESTAMP WITH TIME ZONE,
  FAILURE_REASON  VARCHAR2(1000),
  CREATED_BY      VARCHAR2(36),
  UPDATED_BY      VARCHAR2(36),
  CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  ROW_VERSION     NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_INTEGRATION_CONNECTORS PRIMARY KEY (ID),
  CONSTRAINT FK_INT_CONN_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT FK_INT_CONN_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID),
  CONSTRAINT UQ_INT_CONN_CODE UNIQUE (TENANT_ID, CODE),
  CONSTRAINT CK_INT_CONN_TYPE CHECK (CONNECTOR_TYPE IN ('webhook','delivery_marketplace','accounting','payment_terminal','fiscal','loyalty','custom')),
  CONSTRAINT CK_INT_CONN_AUTH CHECK (AUTH_TYPE IN ('none','api_key','basic','bearer','oauth2','hmac')),
  CONSTRAINT CK_INT_CONN_STATUS CHECK (STATUS IN ('draft','active','paused','error')),
  CONSTRAINT CK_INT_CONN_ACTIVE CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_INT_CONN_SETTINGS_JSON CHECK (SETTINGS IS NULL OR SETTINGS IS JSON)
);
CREATE INDEX IX_INT_CONN_TENANT ON INTEGRATION_CONNECTORS (TENANT_ID, BRANCH_ID, CONNECTOR_TYPE, STATUS);

CREATE TABLE WEBHOOK_SUBSCRIPTIONS (
  ID              VARCHAR2(36)             NOT NULL,
  TENANT_ID       VARCHAR2(36)             NOT NULL,
  BRANCH_ID       VARCHAR2(36),
  CONNECTOR_ID    VARCHAR2(36),
  NAME            VARCHAR2(200)            NOT NULL,
  TARGET_URL      VARCHAR2(2000)           NOT NULL,
  SECRET_REF      VARCHAR2(300),
  EVENT_PATTERN   VARCHAR2(120) DEFAULT '*' NOT NULL,
  EVENT_FILTER    CLOB,
  HEADERS         CLOB,
  STATUS          VARCHAR2(20) DEFAULT 'active' NOT NULL,
  MAX_ATTEMPTS    NUMBER(3) DEFAULT 5      NOT NULL,
  TIMEOUT_SECONDS NUMBER(5) DEFAULT 15     NOT NULL,
  IS_ACTIVE       NUMBER(1) DEFAULT 1      NOT NULL,
  CREATED_BY      VARCHAR2(36),
  UPDATED_BY      VARCHAR2(36),
  CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  ROW_VERSION     NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_WEBHOOK_SUBSCRIPTIONS PRIMARY KEY (ID),
  CONSTRAINT FK_WH_SUB_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT FK_WH_SUB_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID),
  CONSTRAINT FK_WH_SUB_CONNECTOR FOREIGN KEY (CONNECTOR_ID) REFERENCES INTEGRATION_CONNECTORS (ID) ON DELETE SET NULL,
  CONSTRAINT CK_WH_SUB_STATUS CHECK (STATUS IN ('active','paused','error')),
  CONSTRAINT CK_WH_SUB_ACTIVE CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_WH_SUB_ATTEMPTS CHECK (MAX_ATTEMPTS BETWEEN 1 AND 20),
  CONSTRAINT CK_WH_SUB_TIMEOUT CHECK (TIMEOUT_SECONDS BETWEEN 1 AND 120),
  CONSTRAINT CK_WH_SUB_FILTER_JSON CHECK (EVENT_FILTER IS NULL OR EVENT_FILTER IS JSON),
  CONSTRAINT CK_WH_SUB_HEADERS_JSON CHECK (HEADERS IS NULL OR HEADERS IS JSON)
);
CREATE INDEX IX_WH_SUB_TENANT ON WEBHOOK_SUBSCRIPTIONS (TENANT_ID, BRANCH_ID, STATUS, EVENT_PATTERN);

CREATE TABLE INTEGRATION_EVENTS (
  ID              VARCHAR2(36)             NOT NULL,
  TENANT_ID       VARCHAR2(36)             NOT NULL,
  BRANCH_ID       VARCHAR2(36),
  SOURCE_MODULE   VARCHAR2(80)             NOT NULL,
  EVENT_TYPE      VARCHAR2(120)            NOT NULL,
  AGGREGATE_TYPE  VARCHAR2(80)             NOT NULL,
  AGGREGATE_ID    VARCHAR2(100)            NOT NULL,
  PAYLOAD         CLOB                     NOT NULL,
  CORRELATION_ID  VARCHAR2(100),
  STATUS          VARCHAR2(20) DEFAULT 'pending' NOT NULL,
  ATTEMPTS        NUMBER(5) DEFAULT 0      NOT NULL,
  NEXT_ATTEMPT_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY      VARCHAR2(36),
  CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  PROCESSED_AT    TIMESTAMP WITH TIME ZONE,
  ROW_VERSION     NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_INTEGRATION_EVENTS PRIMARY KEY (ID),
  CONSTRAINT FK_INT_EVENT_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT FK_INT_EVENT_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID),
  CONSTRAINT CK_INT_EVENT_STATUS CHECK (STATUS IN ('pending','processing','delivered','failed','cancelled')),
  CONSTRAINT CK_INT_EVENT_PAYLOAD_JSON CHECK (PAYLOAD IS JSON)
);
CREATE INDEX IX_INT_EVENT_PENDING ON INTEGRATION_EVENTS (TENANT_ID, STATUS, NEXT_ATTEMPT_AT, CREATED_AT);
CREATE INDEX IX_INT_EVENT_AGGREGATE ON INTEGRATION_EVENTS (TENANT_ID, AGGREGATE_TYPE, AGGREGATE_ID);

CREATE TABLE WEBHOOK_DELIVERIES (
  ID              VARCHAR2(36)             NOT NULL,
  TENANT_ID       VARCHAR2(36)             NOT NULL,
  EVENT_ID        VARCHAR2(36)             NOT NULL,
  SUBSCRIPTION_ID VARCHAR2(36)             NOT NULL,
  ATTEMPT_NO      NUMBER(3)                NOT NULL,
  STATUS          VARCHAR2(20) DEFAULT 'pending' NOT NULL,
  STATUS_CODE     NUMBER(5),
  REQUEST_HEADERS CLOB,
  RESPONSE_BODY   CLOB,
  ERROR_MESSAGE   VARCHAR2(1000),
  LATENCY_MS      NUMBER(10),
  NEXT_ATTEMPT_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  SENT_AT         TIMESTAMP WITH TIME ZONE,
  CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_WEBHOOK_DELIVERIES PRIMARY KEY (ID),
  CONSTRAINT FK_WH_DEL_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT FK_WH_DEL_EVENT FOREIGN KEY (EVENT_ID) REFERENCES INTEGRATION_EVENTS (ID) ON DELETE CASCADE,
  CONSTRAINT FK_WH_DEL_SUB FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES WEBHOOK_SUBSCRIPTIONS (ID) ON DELETE CASCADE,
  CONSTRAINT UQ_WH_DEL_ATTEMPT UNIQUE (EVENT_ID, SUBSCRIPTION_ID, ATTEMPT_NO),
  CONSTRAINT CK_WH_DEL_STATUS CHECK (STATUS IN ('pending','success','failed','cancelled')),
  CONSTRAINT CK_WH_DEL_HEADERS_JSON CHECK (REQUEST_HEADERS IS NULL OR REQUEST_HEADERS IS JSON)
);
CREATE INDEX IX_WH_DEL_PENDING ON WEBHOOK_DELIVERIES (TENANT_ID, STATUS, NEXT_ATTEMPT_AT, CREATED_AT);
CREATE INDEX IX_WH_DEL_EVENT ON WEBHOOK_DELIVERIES (EVENT_ID, STATUS);

CREATE TABLE INTEGRATION_TERMINALS (
  ID                   VARCHAR2(36)             NOT NULL,
  TENANT_ID            VARCHAR2(36)             NOT NULL,
  BRANCH_ID            VARCHAR2(36)             NOT NULL,
  CONNECTOR_ID         VARCHAR2(36),
  DEVICE_ID            VARCHAR2(36),
  NAME                 VARCHAR2(160)            NOT NULL,
  TERMINAL_TYPE        VARCHAR2(30)             NOT NULL,
  PROVIDER_TERMINAL_ID VARCHAR2(120),
  CONNECTION_MODE      VARCHAR2(30) DEFAULT 'cloud' NOT NULL,
  IP_ADDRESS           VARCHAR2(64),
  PORT                 NUMBER(6),
  SERIAL_PATH          VARCHAR2(120),
  SETTINGS             CLOB,
  IS_ACTIVE            NUMBER(1) DEFAULT 1      NOT NULL,
  LAST_SEEN_AT         TIMESTAMP WITH TIME ZONE,
  CREATED_BY           VARCHAR2(36),
  UPDATED_BY           VARCHAR2(36),
  CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  ROW_VERSION          NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_INTEGRATION_TERMINALS PRIMARY KEY (ID),
  CONSTRAINT FK_INT_TERM_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT FK_INT_TERM_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID),
  CONSTRAINT FK_INT_TERM_CONNECTOR FOREIGN KEY (CONNECTOR_ID) REFERENCES INTEGRATION_CONNECTORS (ID) ON DELETE SET NULL,
  CONSTRAINT FK_INT_TERM_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES DEVICES (ID) ON DELETE SET NULL,
  CONSTRAINT CK_INT_TERM_TYPE CHECK (TERMINAL_TYPE IN ('payment','fiscal','kitchen_printer','cash_drawer','scale','custom')),
  CONSTRAINT CK_INT_TERM_MODE CHECK (CONNECTION_MODE IN ('usb','serial','ethernet','cloud','app_to_app','custom')),
  CONSTRAINT CK_INT_TERM_ACTIVE CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_INT_TERM_SETTINGS_JSON CHECK (SETTINGS IS NULL OR SETTINGS IS JSON)
);
CREATE INDEX IX_INT_TERM_BRANCH ON INTEGRATION_TERMINALS (TENANT_ID, BRANCH_ID, TERMINAL_TYPE, IS_ACTIVE);

CREATE TABLE INTEGRATION_COMMANDS (
  ID                 VARCHAR2(36)             NOT NULL,
  TENANT_ID          VARCHAR2(36)             NOT NULL,
  BRANCH_ID          VARCHAR2(36)             NOT NULL,
  CONNECTOR_ID       VARCHAR2(36),
  TERMINAL_ID        VARCHAR2(36),
  ORDER_ID           VARCHAR2(36),
  PAYMENT_ID         VARCHAR2(36),
  COMMAND_TYPE       VARCHAR2(40)             NOT NULL,
  IDEMPOTENCY_KEY    VARCHAR2(120),
  PAYLOAD            CLOB                     NOT NULL,
  STATUS             VARCHAR2(20) DEFAULT 'queued' NOT NULL,
  PROVIDER_REFERENCE VARCHAR2(160),
  RESULT_PAYLOAD     CLOB,
  ERROR_CODE         VARCHAR2(100),
  ERROR_MESSAGE      VARCHAR2(1000),
  REQUESTED_BY       VARCHAR2(36),
  CREATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  SENT_AT            TIMESTAMP WITH TIME ZONE,
  COMPLETED_AT       TIMESTAMP WITH TIME ZONE,
  ROW_VERSION        NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_INTEGRATION_COMMANDS PRIMARY KEY (ID),
  CONSTRAINT FK_INT_CMD_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT FK_INT_CMD_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID),
  CONSTRAINT FK_INT_CMD_CONNECTOR FOREIGN KEY (CONNECTOR_ID) REFERENCES INTEGRATION_CONNECTORS (ID) ON DELETE SET NULL,
  CONSTRAINT FK_INT_CMD_TERMINAL FOREIGN KEY (TERMINAL_ID) REFERENCES INTEGRATION_TERMINALS (ID) ON DELETE SET NULL,
  CONSTRAINT FK_INT_CMD_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID) ON DELETE SET NULL,
  CONSTRAINT FK_INT_CMD_PAYMENT FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENTS (ID) ON DELETE SET NULL,
  CONSTRAINT UQ_INT_CMD_IDEMPOTENCY UNIQUE (TENANT_ID, IDEMPOTENCY_KEY),
  CONSTRAINT CK_INT_CMD_TYPE CHECK (COMMAND_TYPE IN ('sale','refund','void','settlement','print','open_drawer','custom')),
  CONSTRAINT CK_INT_CMD_STATUS CHECK (STATUS IN ('queued','sent','completed','failed','cancelled')),
  CONSTRAINT CK_INT_CMD_PAYLOAD_JSON CHECK (PAYLOAD IS JSON),
  CONSTRAINT CK_INT_CMD_RESULT_JSON CHECK (RESULT_PAYLOAD IS NULL OR RESULT_PAYLOAD IS JSON)
);
CREATE INDEX IX_INT_CMD_QUEUE ON INTEGRATION_COMMANDS (TENANT_ID, BRANCH_ID, STATUS, CREATED_AT);
CREATE INDEX IX_INT_CMD_TERMINAL ON INTEGRATION_COMMANDS (TENANT_ID, TERMINAL_ID, STATUS);

INSERT INTO SYNC_ENTITY_CONFIG (ENTITY_NAME, TABLE_NAME, IS_BRANCH_SCOPED, ALLOW_CLIENT_PUSH, SORT_ORDER)
VALUES ('integration.connectors', 'INTEGRATION_CONNECTORS', 0, 0, 130);
INSERT INTO SYNC_ENTITY_CONFIG (ENTITY_NAME, TABLE_NAME, IS_BRANCH_SCOPED, ALLOW_CLIENT_PUSH, SORT_ORDER)
VALUES ('integration.terminals', 'INTEGRATION_TERMINALS', 1, 0, 140);
INSERT INTO SYNC_ENTITY_CONFIG (ENTITY_NAME, TABLE_NAME, IS_BRANCH_SCOPED, ALLOW_CLIENT_PUSH, SORT_ORDER)
VALUES ('integration.commands', 'INTEGRATION_COMMANDS', 1, 0, 150);
