
CREATE TABLE PLATFORM_SETTINGS (
  ID            VARCHAR2(36)             NOT NULL,
  TENANT_ID     VARCHAR2(36)             NOT NULL,
  BRANCH_ID     VARCHAR2(36),
  SETTING_KEY   VARCHAR2(128)            NOT NULL,
  SETTING_VALUE CLOB,
  IS_ACTIVE     NUMBER(1)  DEFAULT 1     NOT NULL,
  CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY    VARCHAR2(36),
  UPDATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY    VARCHAR2(36),
  ROW_VERSION   NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_PLATFORM_SETTINGS  PRIMARY KEY (ID),
  CONSTRAINT UQ_PLATFORM_SETTINGS  UNIQUE (TENANT_ID, BRANCH_ID, SETTING_KEY),
  CONSTRAINT CK_PLATFORM_SET_ACTIVE CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_PLATFORM_SET_JSON   CHECK (SETTING_VALUE IS NULL OR SETTING_VALUE IS JSON)
);

CREATE INDEX IX_PLATFORM_SETTINGS_TENANT ON PLATFORM_SETTINGS (TENANT_ID, BRANCH_ID);

COMMENT ON TABLE PLATFORM_SETTINGS IS 'Tenant/branch scoped key-value configuration; baseline object proving the portable schema conventions.';
