
CREATE TABLE FIN_ACCOUNTS (
  ID              VARCHAR2(36)             NOT NULL,
  TENANT_ID       VARCHAR2(36)             NOT NULL,
  BRANCH_ID       VARCHAR2(36),
  NAME            VARCHAR2(160)            NOT NULL,
  ACCOUNT_TYPE    VARCHAR2(24)             NOT NULL,
  CURRENCY        VARCHAR2(3) DEFAULT 'TRY' NOT NULL,
  OPENING_BALANCE NUMBER(18,4) DEFAULT 0   NOT NULL,
  IS_ACTIVE       NUMBER(1) DEFAULT 1      NOT NULL,
  CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  ROW_VERSION     NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_FIN_ACCOUNTS PRIMARY KEY (ID),
  CONSTRAINT FK_FIN_ACCT_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT FK_FIN_ACCT_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID),
  CONSTRAINT CK_FIN_ACCT_TYPE CHECK (ACCOUNT_TYPE IN ('cash','bank','card','online','supplier','customer','other')),
  CONSTRAINT CK_FIN_ACCT_ACTIVE CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT UQ_FIN_ACCT_NAME UNIQUE (TENANT_ID, BRANCH_ID, NAME)
);
CREATE INDEX IX_FIN_ACCT_TENANT ON FIN_ACCOUNTS (TENANT_ID, BRANCH_ID, ACCOUNT_TYPE, IS_ACTIVE);

CREATE TABLE FIN_COUNTERPARTIES (
  ID                VARCHAR2(36)             NOT NULL,
  TENANT_ID         VARCHAR2(36)             NOT NULL,
  COUNTERPARTY_TYPE VARCHAR2(24)             NOT NULL,
  REF_ID            VARCHAR2(36),
  NAME              VARCHAR2(200)            NOT NULL,
  PHONE             VARCHAR2(40),
  EMAIL             VARCHAR2(160),
  TAX_NO            VARCHAR2(40),
  IS_ACTIVE         NUMBER(1) DEFAULT 1      NOT NULL,
  CREATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  ROW_VERSION       NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_FIN_COUNTERPARTIES PRIMARY KEY (ID),
  CONSTRAINT FK_FIN_CP_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT CK_FIN_CP_TYPE CHECK (COUNTERPARTY_TYPE IN ('customer','supplier','staff','other')),
  CONSTRAINT CK_FIN_CP_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);
CREATE INDEX IX_FIN_CP_TENANT ON FIN_COUNTERPARTIES (TENANT_ID, COUNTERPARTY_TYPE, IS_ACTIVE);

CREATE TABLE FIN_TRANSACTIONS (
  ID              VARCHAR2(36)             NOT NULL,
  TENANT_ID       VARCHAR2(36)             NOT NULL,
  BRANCH_ID       VARCHAR2(36)             NOT NULL,
  ACCOUNT_ID      VARCHAR2(36),
  COUNTERPARTY_ID VARCHAR2(36),
  TXN_TYPE        VARCHAR2(24)             NOT NULL,
  CATEGORY        VARCHAR2(120)            NOT NULL,
  METHOD          VARCHAR2(24)             NOT NULL,
  AMOUNT          NUMBER(18,4)             NOT NULL,
  TAX_AMOUNT      NUMBER(18,4) DEFAULT 0   NOT NULL,
  BUSINESS_DATE   DATE                     NOT NULL,
  DESCRIPTION     VARCHAR2(500),
  SOURCE_MODULE   VARCHAR2(60),
  SOURCE_ID       VARCHAR2(60),
  IS_VOIDED       NUMBER(1) DEFAULT 0      NOT NULL,
  CREATED_BY      VARCHAR2(36),
  CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  ROW_VERSION     NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_FIN_TRANSACTIONS PRIMARY KEY (ID),
  CONSTRAINT FK_FIN_TX_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT FK_FIN_TX_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID),
  CONSTRAINT FK_FIN_TX_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES FIN_ACCOUNTS (ID) ON DELETE SET NULL,
  CONSTRAINT FK_FIN_TX_CP FOREIGN KEY (COUNTERPARTY_ID) REFERENCES FIN_COUNTERPARTIES (ID) ON DELETE SET NULL,
  CONSTRAINT CK_FIN_TX_TYPE CHECK (TXN_TYPE IN ('income','expense','adjustment')),
  CONSTRAINT CK_FIN_TX_METHOD CHECK (METHOD IN ('cash','card','bank','online','meal_voucher','on_account','other')),
  CONSTRAINT CK_FIN_TX_AMOUNT CHECK (AMOUNT > 0),
  CONSTRAINT CK_FIN_TX_TAX CHECK (TAX_AMOUNT >= 0),
  CONSTRAINT CK_FIN_TX_VOID CHECK (IS_VOIDED IN (0,1))
);
CREATE INDEX IX_FIN_TX_TENANT_DATE ON FIN_TRANSACTIONS (TENANT_ID, BRANCH_ID, BUSINESS_DATE, TXN_TYPE);
CREATE INDEX IX_FIN_TX_ACCOUNT ON FIN_TRANSACTIONS (ACCOUNT_ID, BUSINESS_DATE);
CREATE INDEX IX_FIN_TX_CP ON FIN_TRANSACTIONS (COUNTERPARTY_ID, BUSINESS_DATE);

CREATE TABLE PRINT_TEMPLATES (
  ID            VARCHAR2(36)             NOT NULL,
  TENANT_ID     VARCHAR2(36)             NOT NULL,
  BRANCH_ID     VARCHAR2(36),
  TEMPLATE_TYPE VARCHAR2(24)             NOT NULL,
  NAME          VARCHAR2(160)            NOT NULL,
  BODY          CLOB                     NOT NULL,
  IS_DEFAULT    NUMBER(1) DEFAULT 0      NOT NULL,
  IS_ACTIVE     NUMBER(1) DEFAULT 1      NOT NULL,
  CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  ROW_VERSION   NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_PRINT_TEMPLATES PRIMARY KEY (ID),
  CONSTRAINT FK_PRINT_TMPL_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT FK_PRINT_TMPL_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID),
  CONSTRAINT CK_PRINT_TMPL_TYPE CHECK (TEMPLATE_TYPE IN ('receipt','kitchen_ticket')),
  CONSTRAINT CK_PRINT_TMPL_DEF CHECK (IS_DEFAULT IN (0,1)),
  CONSTRAINT CK_PRINT_TMPL_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);
CREATE INDEX IX_PRINT_TMPL_TENANT ON PRINT_TEMPLATES (TENANT_ID, BRANCH_ID, TEMPLATE_TYPE, IS_ACTIVE);

CREATE TABLE PRINT_JOBS (
  ID            VARCHAR2(36)             NOT NULL,
  TENANT_ID     VARCHAR2(36)             NOT NULL,
  BRANCH_ID     VARCHAR2(36)             NOT NULL,
  JOB_TYPE      VARCHAR2(24)             NOT NULL,
  ORDER_ID      VARCHAR2(36)             NOT NULL,
  TERMINAL_ID   VARCHAR2(36),
  STATUS        VARCHAR2(20) DEFAULT 'queued' NOT NULL,
  COPIES        NUMBER(3) DEFAULT 1      NOT NULL,
  PAYLOAD       CLOB                     NOT NULL,
  ERROR_MESSAGE VARCHAR2(1000),
  CREATED_BY    VARCHAR2(36),
  CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  ROW_VERSION   NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_PRINT_JOBS PRIMARY KEY (ID),
  CONSTRAINT FK_PRINT_JOB_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT FK_PRINT_JOB_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID),
  CONSTRAINT FK_PRINT_JOB_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID) ON DELETE CASCADE,
  CONSTRAINT FK_PRINT_JOB_TERM FOREIGN KEY (TERMINAL_ID) REFERENCES INTEGRATION_TERMINALS (ID) ON DELETE SET NULL,
  CONSTRAINT CK_PRINT_JOB_TYPE CHECK (JOB_TYPE IN ('receipt','kitchen_ticket')),
  CONSTRAINT CK_PRINT_JOB_STATUS CHECK (STATUS IN ('queued','sent','printed','failed','cancelled')),
  CONSTRAINT CK_PRINT_JOB_COPIES CHECK (COPIES BETWEEN 1 AND 9),
  CONSTRAINT CK_PRINT_JOB_PAYLOAD CHECK (PAYLOAD IS JSON)
);
CREATE INDEX IX_PRINT_JOB_QUEUE ON PRINT_JOBS (TENANT_ID, BRANCH_ID, STATUS, CREATED_AT);
CREATE INDEX IX_PRINT_JOB_ORDER ON PRINT_JOBS (ORDER_ID, CREATED_AT);

INSERT INTO SYNC_ENTITY_CONFIG (ENTITY_NAME, TABLE_NAME, IS_BRANCH_SCOPED, ALLOW_CLIENT_PUSH, SORT_ORDER)
VALUES ('finance.accounts', 'FIN_ACCOUNTS', 0, 0, 160);
INSERT INTO SYNC_ENTITY_CONFIG (ENTITY_NAME, TABLE_NAME, IS_BRANCH_SCOPED, ALLOW_CLIENT_PUSH, SORT_ORDER)
VALUES ('finance.counterparties', 'FIN_COUNTERPARTIES', 0, 0, 170);
INSERT INTO SYNC_ENTITY_CONFIG (ENTITY_NAME, TABLE_NAME, IS_BRANCH_SCOPED, ALLOW_CLIENT_PUSH, SORT_ORDER)
VALUES ('finance.transactions', 'FIN_TRANSACTIONS', 1, 1, 180);
INSERT INTO SYNC_ENTITY_CONFIG (ENTITY_NAME, TABLE_NAME, IS_BRANCH_SCOPED, ALLOW_CLIENT_PUSH, SORT_ORDER)
VALUES ('print.jobs', 'PRINT_JOBS', 1, 0, 190);
