
CREATE TABLE EINVOICE_DOCUMENTS (
  ID               VARCHAR2(36)             NOT NULL,
  TENANT_ID        VARCHAR2(36)             NOT NULL,
  BRANCH_ID        VARCHAR2(36),
  ORDER_ID         VARCHAR2(36),
  INVOICE_ID       VARCHAR2(36),
  DOCUMENT_TYPE    VARCHAR2(16)             NOT NULL,
  PROVIDER         VARCHAR2(40)             NOT NULL,
  SCENARIO         VARCHAR2(24) DEFAULT 'TICARIFATURA' NOT NULL,
  STATUS           VARCHAR2(24) DEFAULT 'draft' NOT NULL,
  EXTERNAL_ID      VARCHAR2(120),
  DOC_UUID         VARCHAR2(64),
  INVOICE_NUMBER   VARCHAR2(40),
  BUYER_NAME       VARCHAR2(200),
  BUYER_TAX_NO     VARCHAR2(20),
  CURRENCY         VARCHAR2(3)  DEFAULT 'TRY' NOT NULL,
  SUBTOTAL         NUMBER(18,4) DEFAULT 0    NOT NULL,
  TAX_TOTAL        NUMBER(18,4) DEFAULT 0    NOT NULL,
  GRAND_TOTAL      NUMBER(18,4) DEFAULT 0    NOT NULL,
  REQUEST_PAYLOAD  CLOB,
  RESPONSE_PAYLOAD CLOB,
  PDF_URL          VARCHAR2(400),
  ERROR_MESSAGE    VARCHAR2(1000),
  ISSUED_AT        TIMESTAMP WITH TIME ZONE,
  CREATED_BY       VARCHAR2(36),
  CREATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  ROW_VERSION      NUMBER(19)   DEFAULT 1    NOT NULL,
  CONSTRAINT PK_EINVOICE_DOCUMENTS PRIMARY KEY (ID),
  CONSTRAINT FK_EINV_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT CK_EINV_TYPE   CHECK (DOCUMENT_TYPE IN ('efatura','earsiv')),
  CONSTRAINT CK_EINV_STATUS CHECK (STATUS IN ('draft','sent','accepted','rejected','cancelled','error')),
  CONSTRAINT CK_EINV_REQ_JSON  CHECK (REQUEST_PAYLOAD IS JSON),
  CONSTRAINT CK_EINV_RESP_JSON CHECK (RESPONSE_PAYLOAD IS JSON)
);

CREATE INDEX IX_EINV_ORDER  ON EINVOICE_DOCUMENTS (TENANT_ID, ORDER_ID);
CREATE INDEX IX_EINV_STATUS ON EINVOICE_DOCUMENTS (TENANT_ID, STATUS, CREATED_AT);
