
CREATE TABLE FISCAL_TRANSACTIONS (
  ID                 VARCHAR2(36)             NOT NULL,
  TENANT_ID          VARCHAR2(36)             NOT NULL,
  BRANCH_ID          VARCHAR2(36),
  ORDER_ID           VARCHAR2(36),
  PAYMENT_ID         VARCHAR2(36),
  COMMAND_ID         VARCHAR2(36),
  TERMINAL_ID        VARCHAR2(36),
  PROVIDER           VARCHAR2(80)             NOT NULL,
  METHOD             VARCHAR2(30)             NOT NULL,
  AMOUNT             NUMBER(18,4) DEFAULT 0   NOT NULL,
  TIP_AMOUNT         NUMBER(18,4) DEFAULT 0   NOT NULL,
  CURRENCY           VARCHAR2(3)  DEFAULT 'TRY' NOT NULL,
  STATUS             VARCHAR2(30) DEFAULT 'queued' NOT NULL,
  AUTHORIZATION_CODE VARCHAR2(120),
  BATCH_NO           VARCHAR2(80),
  STAN               VARCHAR2(80),
  RRN                VARCHAR2(80),
  FISCAL_RECEIPT_NO  VARCHAR2(120),
  Z_NO               VARCHAR2(120),
  DEVICE_SERIAL      VARCHAR2(120),
  DOCUMENT_UUID      VARCHAR2(80),
  ERROR_CODE         VARCHAR2(100),
  ERROR_MESSAGE      VARCHAR2(1000),
  REQUEST_PAYLOAD    CLOB,
  RESPONSE_PAYLOAD   CLOB,
  CREATED_BY         VARCHAR2(36),
  CREATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  COMPLETED_AT       TIMESTAMP WITH TIME ZONE,
  ROW_VERSION        NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_FISCAL_TRANSACTIONS PRIMARY KEY (ID),
  CONSTRAINT FK_FISCAL_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT FK_FISCAL_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID),
  CONSTRAINT FK_FISCAL_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID) ON DELETE SET NULL,
  CONSTRAINT FK_FISCAL_PAYMENT FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENTS (ID) ON DELETE SET NULL,
  CONSTRAINT FK_FISCAL_COMMAND FOREIGN KEY (COMMAND_ID) REFERENCES INTEGRATION_COMMANDS (ID) ON DELETE SET NULL,
  CONSTRAINT FK_FISCAL_TERMINAL FOREIGN KEY (TERMINAL_ID) REFERENCES INTEGRATION_TERMINALS (ID) ON DELETE SET NULL,
  CONSTRAINT CK_FISCAL_METHOD CHECK (METHOD IN ('cash','card','meal_voucher','other')),
  CONSTRAINT CK_FISCAL_STATUS CHECK (STATUS IN ('queued','sent','completed','failed','cancelled','manual_override','paid_document_pending')),
  CONSTRAINT CK_FISCAL_REQ_JSON CHECK (REQUEST_PAYLOAD IS NULL OR REQUEST_PAYLOAD IS JSON),
  CONSTRAINT CK_FISCAL_RESP_JSON CHECK (RESPONSE_PAYLOAD IS NULL OR RESPONSE_PAYLOAD IS JSON)
);

CREATE INDEX IX_FISCAL_ORDER ON FISCAL_TRANSACTIONS (TENANT_ID, ORDER_ID, CREATED_AT);
CREATE INDEX IX_FISCAL_STATUS ON FISCAL_TRANSACTIONS (TENANT_ID, BRANCH_ID, STATUS, CREATED_AT);
CREATE INDEX IX_FISCAL_TERMINAL ON FISCAL_TRANSACTIONS (TENANT_ID, TERMINAL_ID, CREATED_AT);

INSERT INTO SYNC_ENTITY_CONFIG (ENTITY_NAME, TABLE_NAME, IS_BRANCH_SCOPED, ALLOW_CLIENT_PUSH, SORT_ORDER)
VALUES ('fiscal.transactions', 'FISCAL_TRANSACTIONS', 1, 0, 160);
