
CREATE TABLE TENANTS (
  ID          VARCHAR2(36)             NOT NULL,
  NAME        VARCHAR2(200)            NOT NULL,
  SLUG        VARCHAR2(100)            NOT NULL,
  IS_ACTIVE   NUMBER(1)  DEFAULT 1     NOT NULL,
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY  VARCHAR2(36),
  UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY  VARCHAR2(36),
  ROW_VERSION NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_TENANTS PRIMARY KEY (ID),
  CONSTRAINT UQ_TENANTS_SLUG UNIQUE (SLUG),
  CONSTRAINT CK_TENANTS_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);

CREATE TABLE BRANCHES (
  ID          VARCHAR2(36)             NOT NULL,
  TENANT_ID   VARCHAR2(36)             NOT NULL,
  NAME        VARCHAR2(200)            NOT NULL,
  CODE        VARCHAR2(40)             NOT NULL,
  TIME_ZONE   VARCHAR2(64)  DEFAULT 'Europe/Istanbul' NOT NULL,
  CURRENCY    VARCHAR2(3)   DEFAULT 'TRY' NOT NULL,
  IS_ACTIVE   NUMBER(1)  DEFAULT 1     NOT NULL,
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY  VARCHAR2(36),
  UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY  VARCHAR2(36),
  ROW_VERSION NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_BRANCHES PRIMARY KEY (ID),
  CONSTRAINT FK_BRANCHES_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT UQ_BRANCHES_CODE UNIQUE (TENANT_ID, CODE),
  CONSTRAINT CK_BRANCHES_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);
CREATE INDEX IX_BRANCHES_TENANT ON BRANCHES (TENANT_ID);

CREATE TABLE ROLES (
  ID          VARCHAR2(36)             NOT NULL,
  TENANT_ID   VARCHAR2(36)             NOT NULL,
  NAME        VARCHAR2(80)             NOT NULL,
  DESCRIPTION VARCHAR2(400),
  IS_SYSTEM   NUMBER(1)  DEFAULT 0     NOT NULL,
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY  VARCHAR2(36),
  UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY  VARCHAR2(36),
  ROW_VERSION NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_ROLES PRIMARY KEY (ID),
  CONSTRAINT FK_ROLES_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT UQ_ROLES_NAME UNIQUE (TENANT_ID, NAME),
  CONSTRAINT CK_ROLES_SYSTEM CHECK (IS_SYSTEM IN (0,1))
);
CREATE INDEX IX_ROLES_TENANT ON ROLES (TENANT_ID);

CREATE TABLE PERMISSIONS (
  ID          VARCHAR2(36)             NOT NULL,
  CODE        VARCHAR2(100)            NOT NULL,
  DESCRIPTION VARCHAR2(400),
  CONSTRAINT PK_PERMISSIONS PRIMARY KEY (ID),
  CONSTRAINT UQ_PERMISSIONS_CODE UNIQUE (CODE)
);

CREATE TABLE ROLE_PERMISSIONS (
  ROLE_ID       VARCHAR2(36) NOT NULL,
  PERMISSION_ID VARCHAR2(36) NOT NULL,
  CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_ROLE_PERMISSIONS PRIMARY KEY (ROLE_ID, PERMISSION_ID),
  CONSTRAINT FK_ROLEPERM_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE,
  CONSTRAINT FK_ROLEPERM_PERM FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS (ID) ON DELETE CASCADE
);

CREATE TABLE USERS (
  ID                   VARCHAR2(36)             NOT NULL,
  TENANT_ID            VARCHAR2(36)             NOT NULL,
  EMAIL                VARCHAR2(255)            NOT NULL,
  FULL_NAME            VARCHAR2(200)            NOT NULL,
  PASSWORD_HASH        VARCHAR2(255)            NOT NULL,
  PIN_HASH             VARCHAR2(255),
  IS_ACTIVE            NUMBER(1)  DEFAULT 1     NOT NULL,
  MUST_CHANGE_PASSWORD NUMBER(1)  DEFAULT 0     NOT NULL,
  FAILED_ATTEMPTS      NUMBER(5)  DEFAULT 0     NOT NULL,
  LOCKED_UNTIL         TIMESTAMP WITH TIME ZONE,
  LAST_LOGIN_AT        TIMESTAMP WITH TIME ZONE,
  CREATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY           VARCHAR2(36),
  UPDATED_AT           TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY           VARCHAR2(36),
  ROW_VERSION          NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_USERS PRIMARY KEY (ID),
  CONSTRAINT FK_USERS_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT UQ_USERS_EMAIL UNIQUE (TENANT_ID, EMAIL),
  CONSTRAINT CK_USERS_ACTIVE CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_USERS_MCP CHECK (MUST_CHANGE_PASSWORD IN (0,1))
);
CREATE INDEX IX_USERS_TENANT ON USERS (TENANT_ID);

CREATE TABLE USER_ROLES (
  USER_ID    VARCHAR2(36) NOT NULL,
  ROLE_ID    VARCHAR2(36) NOT NULL,
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_USER_ROLES PRIMARY KEY (USER_ID, ROLE_ID),
  CONSTRAINT FK_USERROLES_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
  CONSTRAINT FK_USERROLES_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE
);

CREATE TABLE USER_BRANCHES (
  USER_ID    VARCHAR2(36) NOT NULL,
  BRANCH_ID  VARCHAR2(36) NOT NULL,
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_USER_BRANCHES PRIMARY KEY (USER_ID, BRANCH_ID),
  CONSTRAINT FK_USERBRANCH_USER   FOREIGN KEY (USER_ID)   REFERENCES USERS (ID) ON DELETE CASCADE,
  CONSTRAINT FK_USERBRANCH_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID) ON DELETE CASCADE
);

CREATE TABLE DEVICES (
  ID           VARCHAR2(36)             NOT NULL,
  TENANT_ID    VARCHAR2(36)             NOT NULL,
  BRANCH_ID    VARCHAR2(36),
  NAME         VARCHAR2(120)            NOT NULL,
  DEVICE_TYPE  VARCHAR2(30)  DEFAULT 'pos' NOT NULL,
  FINGERPRINT  VARCHAR2(200)            NOT NULL,
  ALLOWED_IP   VARCHAR2(64),
  IS_APPROVED  NUMBER(1)  DEFAULT 0     NOT NULL,
  LAST_SEEN_AT TIMESTAMP WITH TIME ZONE,
  CREATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY   VARCHAR2(36),
  UPDATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY   VARCHAR2(36),
  ROW_VERSION  NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_DEVICES PRIMARY KEY (ID),
  CONSTRAINT FK_DEVICES_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT FK_DEVICES_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID),
  CONSTRAINT UQ_DEVICES_FP UNIQUE (TENANT_ID, FINGERPRINT),
  CONSTRAINT CK_DEVICES_APPROVED CHECK (IS_APPROVED IN (0,1))
);
CREATE INDEX IX_DEVICES_TENANT ON DEVICES (TENANT_ID);

CREATE TABLE REFRESH_TOKENS (
  ID                  VARCHAR2(36)             NOT NULL,
  USER_ID             VARCHAR2(36)             NOT NULL,
  TENANT_ID           VARCHAR2(36)             NOT NULL,
  DEVICE_ID           VARCHAR2(36),
  TOKEN_HASH          VARCHAR2(128)            NOT NULL,
  EXPIRES_AT          TIMESTAMP WITH TIME ZONE NOT NULL,
  REVOKED_AT          TIMESTAMP WITH TIME ZONE,
  REPLACED_BY_TOKEN_ID VARCHAR2(36),
  CREATED_IP          VARCHAR2(64),
  CREATED_AT          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_REFRESH_TOKENS PRIMARY KEY (ID),
  CONSTRAINT FK_RT_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
  CONSTRAINT UQ_RT_HASH UNIQUE (TOKEN_HASH)
);
CREATE INDEX IX_RT_USER ON REFRESH_TOKENS (USER_ID);

CREATE TABLE AUDIT_LOG (
  ID          VARCHAR2(36)             NOT NULL,
  TENANT_ID   VARCHAR2(36),
  USER_ID     VARCHAR2(36),
  ACTION      VARCHAR2(100)            NOT NULL,
  ENTITY_TYPE VARCHAR2(100),
  ENTITY_ID   VARCHAR2(100),
  DETAIL      CLOB,
  IP_ADDRESS  VARCHAR2(64),
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (ID),
  CONSTRAINT CK_AUDIT_JSON CHECK (DETAIL IS NULL OR DETAIL IS JSON)
);
CREATE INDEX IX_AUDIT_TENANT_TIME ON AUDIT_LOG (TENANT_ID, CREATED_AT);
