
CREATE TABLE MENU_CATEGORIES (
  ID          VARCHAR2(36)             NOT NULL,
  TENANT_ID   VARCHAR2(36)             NOT NULL,
  BRANCH_ID   VARCHAR2(36),
  NAME        VARCHAR2(150)            NOT NULL,
  COLOR       VARCHAR2(16),
  SORT_ORDER  NUMBER(6)  DEFAULT 0     NOT NULL,
  IS_ACTIVE   NUMBER(1)  DEFAULT 1     NOT NULL,
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY  VARCHAR2(36),
  UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY  VARCHAR2(36),
  ROW_VERSION NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_MENU_CATEGORIES PRIMARY KEY (ID),
  CONSTRAINT FK_MENUCAT_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT UQ_MENUCAT_NAME UNIQUE (TENANT_ID, NAME),
  CONSTRAINT CK_MENUCAT_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);
CREATE INDEX IX_MENUCAT_TENANT ON MENU_CATEGORIES (TENANT_ID);

CREATE TABLE MENU_ITEMS (
  ID           VARCHAR2(36)             NOT NULL,
  TENANT_ID    VARCHAR2(36)             NOT NULL,
  CATEGORY_ID  VARCHAR2(36)             NOT NULL,
  NAME         VARCHAR2(200)            NOT NULL,
  DESCRIPTION  VARCHAR2(1000),
  PRICE        NUMBER(18,4) DEFAULT 0   NOT NULL,
  VAT_RATE     NUMBER(5,2)  DEFAULT 10  NOT NULL,
  SKU          VARCHAR2(60),
  IMAGE_URL    VARCHAR2(500),
  PREP_STATION VARCHAR2(40),
  SORT_ORDER   NUMBER(6)  DEFAULT 0     NOT NULL,
  IS_ACTIVE    NUMBER(1)  DEFAULT 1     NOT NULL,
  CREATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY   VARCHAR2(36),
  UPDATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY   VARCHAR2(36),
  ROW_VERSION  NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_MENU_ITEMS PRIMARY KEY (ID),
  CONSTRAINT FK_MENUITEM_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT FK_MENUITEM_CAT FOREIGN KEY (CATEGORY_ID) REFERENCES MENU_CATEGORIES (ID),
  CONSTRAINT CK_MENUITEM_ACTIVE CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_MENUITEM_PRICE CHECK (PRICE >= 0)
);
CREATE INDEX IX_MENUITEM_TENANT ON MENU_ITEMS (TENANT_ID);
CREATE INDEX IX_MENUITEM_CAT ON MENU_ITEMS (CATEGORY_ID);

CREATE TABLE MODIFIER_GROUPS (
  ID          VARCHAR2(36)             NOT NULL,
  TENANT_ID   VARCHAR2(36)             NOT NULL,
  NAME        VARCHAR2(150)            NOT NULL,
  MIN_SELECT  NUMBER(4)  DEFAULT 0     NOT NULL,
  MAX_SELECT  NUMBER(4)  DEFAULT 1     NOT NULL,
  IS_REQUIRED NUMBER(1)  DEFAULT 0     NOT NULL,
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY  VARCHAR2(36),
  UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY  VARCHAR2(36),
  ROW_VERSION NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_MODIFIER_GROUPS PRIMARY KEY (ID),
  CONSTRAINT FK_MODGRP_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT UQ_MODGRP_NAME UNIQUE (TENANT_ID, NAME),
  CONSTRAINT CK_MODGRP_REQ CHECK (IS_REQUIRED IN (0,1))
);

CREATE TABLE MODIFIERS (
  ID          VARCHAR2(36)             NOT NULL,
  TENANT_ID   VARCHAR2(36)             NOT NULL,
  GROUP_ID    VARCHAR2(36)             NOT NULL,
  NAME        VARCHAR2(150)            NOT NULL,
  PRICE_DELTA NUMBER(18,4) DEFAULT 0   NOT NULL,
  SORT_ORDER  NUMBER(6)  DEFAULT 0     NOT NULL,
  IS_ACTIVE   NUMBER(1)  DEFAULT 1     NOT NULL,
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY  VARCHAR2(36),
  UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY  VARCHAR2(36),
  ROW_VERSION NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_MODIFIERS PRIMARY KEY (ID),
  CONSTRAINT FK_MOD_GROUP FOREIGN KEY (GROUP_ID) REFERENCES MODIFIER_GROUPS (ID) ON DELETE CASCADE,
  CONSTRAINT CK_MOD_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);
CREATE INDEX IX_MOD_GROUP ON MODIFIERS (GROUP_ID);

CREATE TABLE ITEM_MODIFIER_GROUPS (
  ITEM_ID    VARCHAR2(36) NOT NULL,
  GROUP_ID   VARCHAR2(36) NOT NULL,
  SORT_ORDER NUMBER(6) DEFAULT 0 NOT NULL,
  CONSTRAINT PK_ITEM_MODGRP PRIMARY KEY (ITEM_ID, GROUP_ID),
  CONSTRAINT FK_IMG_ITEM  FOREIGN KEY (ITEM_ID)  REFERENCES MENU_ITEMS (ID) ON DELETE CASCADE,
  CONSTRAINT FK_IMG_GROUP FOREIGN KEY (GROUP_ID) REFERENCES MODIFIER_GROUPS (ID) ON DELETE CASCADE
);

CREATE TABLE PRICE_LISTS (
  ID          VARCHAR2(36)             NOT NULL,
  TENANT_ID   VARCHAR2(36)             NOT NULL,
  BRANCH_ID   VARCHAR2(36),
  NAME        VARCHAR2(150)            NOT NULL,
  CHANNEL     VARCHAR2(20) DEFAULT 'dinein' NOT NULL,
  IS_DEFAULT  NUMBER(1)  DEFAULT 0     NOT NULL,
  IS_ACTIVE   NUMBER(1)  DEFAULT 1     NOT NULL,
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY  VARCHAR2(36),
  UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY  VARCHAR2(36),
  ROW_VERSION NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_PRICE_LISTS PRIMARY KEY (ID),
  CONSTRAINT FK_PRICELIST_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT CK_PRICELIST_ACTIVE CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT CK_PRICELIST_DEFAULT CHECK (IS_DEFAULT IN (0,1))
);

CREATE TABLE PRICE_LIST_ITEMS (
  ID            VARCHAR2(36)   NOT NULL,
  PRICE_LIST_ID VARCHAR2(36)   NOT NULL,
  MENU_ITEM_ID  VARCHAR2(36)   NOT NULL,
  PRICE         NUMBER(18,4)   NOT NULL,
  CONSTRAINT PK_PRICE_LIST_ITEMS PRIMARY KEY (ID),
  CONSTRAINT FK_PLI_LIST FOREIGN KEY (PRICE_LIST_ID) REFERENCES PRICE_LISTS (ID) ON DELETE CASCADE,
  CONSTRAINT FK_PLI_ITEM FOREIGN KEY (MENU_ITEM_ID)  REFERENCES MENU_ITEMS (ID) ON DELETE CASCADE,
  CONSTRAINT UQ_PLI UNIQUE (PRICE_LIST_ID, MENU_ITEM_ID),
  CONSTRAINT CK_PLI_PRICE CHECK (PRICE >= 0)
);

CREATE TABLE COMBOS (
  ID          VARCHAR2(36)             NOT NULL,
  TENANT_ID   VARCHAR2(36)             NOT NULL,
  NAME        VARCHAR2(200)            NOT NULL,
  PRICE       NUMBER(18,4) DEFAULT 0   NOT NULL,
  IS_ACTIVE   NUMBER(1)  DEFAULT 1     NOT NULL,
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY  VARCHAR2(36),
  UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY  VARCHAR2(36),
  ROW_VERSION NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_COMBOS PRIMARY KEY (ID),
  CONSTRAINT FK_COMBO_TENANT FOREIGN KEY (TENANT_ID) REFERENCES TENANTS (ID),
  CONSTRAINT CK_COMBO_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);

CREATE TABLE COMBO_ITEMS (
  ID           VARCHAR2(36) NOT NULL,
  COMBO_ID     VARCHAR2(36) NOT NULL,
  MENU_ITEM_ID VARCHAR2(36) NOT NULL,
  QUANTITY     NUMBER(6) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_COMBO_ITEMS PRIMARY KEY (ID),
  CONSTRAINT FK_COMBOITEM_COMBO FOREIGN KEY (COMBO_ID)     REFERENCES COMBOS (ID) ON DELETE CASCADE,
  CONSTRAINT FK_COMBOITEM_ITEM  FOREIGN KEY (MENU_ITEM_ID) REFERENCES MENU_ITEMS (ID),
  CONSTRAINT CK_COMBOITEM_QTY CHECK (QUANTITY > 0)
);

CREATE TABLE ITEM_BARCODES (
  ID           VARCHAR2(36) NOT NULL,
  TENANT_ID    VARCHAR2(36) NOT NULL,
  MENU_ITEM_ID VARCHAR2(36) NOT NULL,
  BARCODE      VARCHAR2(64) NOT NULL,
  CONSTRAINT PK_ITEM_BARCODES PRIMARY KEY (ID),
  CONSTRAINT FK_BARCODE_ITEM FOREIGN KEY (MENU_ITEM_ID) REFERENCES MENU_ITEMS (ID) ON DELETE CASCADE,
  CONSTRAINT UQ_BARCODE UNIQUE (TENANT_ID, BARCODE)
);
