
CREATE SEQUENCE ORDER_NO_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;

CREATE TABLE TABLE_SECTIONS (
  ID          VARCHAR2(36)             NOT NULL,
  TENANT_ID   VARCHAR2(36)             NOT NULL,
  BRANCH_ID   VARCHAR2(36)             NOT NULL,
  NAME        VARCHAR2(120)            NOT NULL,
  SORT_ORDER  NUMBER(6) DEFAULT 0      NOT NULL,
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  ROW_VERSION NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_TABLE_SECTIONS PRIMARY KEY (ID),
  CONSTRAINT FK_SECTION_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID)
);
CREATE INDEX IX_SECTION_TENANT ON TABLE_SECTIONS (TENANT_ID, BRANCH_ID);

CREATE TABLE DINING_TABLES (
  ID          VARCHAR2(36)             NOT NULL,
  TENANT_ID   VARCHAR2(36)             NOT NULL,
  BRANCH_ID   VARCHAR2(36)             NOT NULL,
  SECTION_ID  VARCHAR2(36),
  NAME        VARCHAR2(60)             NOT NULL,
  CAPACITY    NUMBER(4)  DEFAULT 4     NOT NULL,
  STATUS      VARCHAR2(16) DEFAULT 'idle' NOT NULL,
  SORT_ORDER  NUMBER(6)  DEFAULT 0     NOT NULL,
  IS_ACTIVE   NUMBER(1)  DEFAULT 1     NOT NULL,
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  ROW_VERSION NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_DINING_TABLES PRIMARY KEY (ID),
  CONSTRAINT FK_TABLE_BRANCH  FOREIGN KEY (BRANCH_ID)  REFERENCES BRANCHES (ID),
  CONSTRAINT FK_TABLE_SECTION FOREIGN KEY (SECTION_ID) REFERENCES TABLE_SECTIONS (ID),
  CONSTRAINT UQ_TABLE_NAME UNIQUE (BRANCH_ID, NAME),
  CONSTRAINT CK_TABLE_STATUS CHECK (STATUS IN ('idle','occupied')),
  CONSTRAINT CK_TABLE_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);
CREATE INDEX IX_TABLE_TENANT ON DINING_TABLES (TENANT_ID, BRANCH_ID);

CREATE TABLE ORDERS (
  ID             VARCHAR2(36)             NOT NULL,
  TENANT_ID      VARCHAR2(36)             NOT NULL,
  BRANCH_ID      VARCHAR2(36)             NOT NULL,
  ORDER_NO       NUMBER(12)               NOT NULL,
  TABLE_ID       VARCHAR2(36),
  ORDER_TYPE     VARCHAR2(16) DEFAULT 'dinein' NOT NULL,
  STATUS         VARCHAR2(16) DEFAULT 'open' NOT NULL,
  GUEST_COUNT    NUMBER(4)  DEFAULT 1     NOT NULL,
  SUBTOTAL       NUMBER(18,4) DEFAULT 0   NOT NULL,
  DISCOUNT_TOTAL NUMBER(18,4) DEFAULT 0   NOT NULL,
  TAX_TOTAL      NUMBER(18,4) DEFAULT 0   NOT NULL,
  TOTAL          NUMBER(18,4) DEFAULT 0   NOT NULL,
  NOTE           VARCHAR2(1000),
  OPENED_BY      VARCHAR2(36),
  CLOSED_BY      VARCHAR2(36),
  OPENED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CLOSED_AT      TIMESTAMP WITH TIME ZONE,
  UPDATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  ROW_VERSION    NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_ORDERS PRIMARY KEY (ID),
  CONSTRAINT FK_ORDER_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID),
  CONSTRAINT FK_ORDER_TABLE  FOREIGN KEY (TABLE_ID)  REFERENCES DINING_TABLES (ID),
  CONSTRAINT UQ_ORDER_NO UNIQUE (TENANT_ID, ORDER_NO),
  CONSTRAINT CK_ORDER_STATUS CHECK (STATUS IN ('open','closed','cancelled')),
  CONSTRAINT CK_ORDER_TYPE CHECK (ORDER_TYPE IN ('dinein','takeaway','delivery'))
);
CREATE INDEX IX_ORDER_TENANT_STATUS ON ORDERS (TENANT_ID, STATUS);
CREATE INDEX IX_ORDER_TABLE ON ORDERS (TABLE_ID);

CREATE TABLE ORDER_ITEMS (
  ID            VARCHAR2(36)             NOT NULL,
  ORDER_ID      VARCHAR2(36)             NOT NULL,
  TENANT_ID     VARCHAR2(36)             NOT NULL,
  MENU_ITEM_ID  VARCHAR2(36)             NOT NULL,
  NAME_SNAPSHOT VARCHAR2(200)            NOT NULL,
  UNIT_PRICE    NUMBER(18,4)             NOT NULL,
  QUANTITY      NUMBER(9,3)  DEFAULT 1   NOT NULL,
  MODIFIER_TOTAL NUMBER(18,4) DEFAULT 0  NOT NULL,
  LINE_TOTAL    NUMBER(18,4) DEFAULT 0   NOT NULL,
  VAT_RATE      NUMBER(5,2)  DEFAULT 10  NOT NULL,
  COURSE_NO     NUMBER(3)  DEFAULT 1     NOT NULL,
  STATUS        VARCHAR2(16) DEFAULT 'pending' NOT NULL,
  IS_COMP       NUMBER(1)  DEFAULT 0     NOT NULL,
  NOTE          VARCHAR2(500),
  VOID_REASON   VARCHAR2(300),
  CREATED_BY    VARCHAR2(36),
  CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_ORDER_ITEMS PRIMARY KEY (ID),
  CONSTRAINT FK_OITEM_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID) ON DELETE CASCADE,
  CONSTRAINT CK_OITEM_STATUS CHECK (STATUS IN ('pending','in_kitchen','ready','served','void')),
  CONSTRAINT CK_OITEM_COMP CHECK (IS_COMP IN (0,1)),
  CONSTRAINT CK_OITEM_QTY CHECK (QUANTITY > 0)
);
CREATE INDEX IX_OITEM_ORDER ON ORDER_ITEMS (ORDER_ID);

CREATE TABLE ORDER_ITEM_MODIFIERS (
  ID            VARCHAR2(36)  NOT NULL,
  ORDER_ITEM_ID VARCHAR2(36)  NOT NULL,
  MODIFIER_ID   VARCHAR2(36),
  NAME_SNAPSHOT VARCHAR2(150) NOT NULL,
  PRICE_DELTA   NUMBER(18,4) DEFAULT 0 NOT NULL,
  CONSTRAINT PK_ORDER_ITEM_MODIFIERS PRIMARY KEY (ID),
  CONSTRAINT FK_OIM_ITEM FOREIGN KEY (ORDER_ITEM_ID) REFERENCES ORDER_ITEMS (ID) ON DELETE CASCADE
);
CREATE INDEX IX_OIM_ITEM ON ORDER_ITEM_MODIFIERS (ORDER_ITEM_ID);

CREATE TABLE ORDER_DISCOUNTS (
  ID          VARCHAR2(36)  NOT NULL,
  ORDER_ID    VARCHAR2(36)  NOT NULL,
  TENANT_ID   VARCHAR2(36)  NOT NULL,
  DISC_TYPE   VARCHAR2(10)  NOT NULL,
  DISC_VALUE  NUMBER(18,4)  NOT NULL,
  AMOUNT      NUMBER(18,4)  NOT NULL,
  REASON      VARCHAR2(300),
  CREATED_BY  VARCHAR2(36),
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_ORDER_DISCOUNTS PRIMARY KEY (ID),
  CONSTRAINT FK_ODISC_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID) ON DELETE CASCADE,
  CONSTRAINT CK_ODISC_TYPE CHECK (DISC_TYPE IN ('percent','amount'))
);
CREATE INDEX IX_ODISC_ORDER ON ORDER_DISCOUNTS (ORDER_ID);

CREATE TABLE ORDER_TRANSFERS (
  ID              VARCHAR2(36) NOT NULL,
  TENANT_ID       VARCHAR2(36) NOT NULL,
  ORDER_ID        VARCHAR2(36) NOT NULL,
  ACTION          VARCHAR2(16) NOT NULL,
  FROM_TABLE_ID   VARCHAR2(36),
  TO_TABLE_ID     VARCHAR2(36),
  RELATED_ORDER_ID VARCHAR2(36),
  USER_ID         VARCHAR2(36),
  CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_ORDER_TRANSFERS PRIMARY KEY (ID),
  CONSTRAINT CK_OTRANSFER_ACTION CHECK (ACTION IN ('transfer','merge','split'))
);
CREATE INDEX IX_OTRANSFER_ORDER ON ORDER_TRANSFERS (ORDER_ID);
