
CREATE SEQUENCE INVOICE_NO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE PAYMENTS (
  ID          VARCHAR2(36)             NOT NULL,
  TENANT_ID   VARCHAR2(36)             NOT NULL,
  BRANCH_ID   VARCHAR2(36)             NOT NULL,
  ORDER_ID    VARCHAR2(36)             NOT NULL,
  METHOD      VARCHAR2(20)             NOT NULL,
  AMOUNT      NUMBER(18,4)             NOT NULL,
  TIP_AMOUNT  NUMBER(18,4) DEFAULT 0   NOT NULL,
  REFERENCE   VARCHAR2(120),
  IS_VOIDED   NUMBER(1)  DEFAULT 0     NOT NULL,
  CREATED_BY  VARCHAR2(36),
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_PAYMENTS PRIMARY KEY (ID),
  CONSTRAINT FK_PAY_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID),
  CONSTRAINT CK_PAY_METHOD CHECK (METHOD IN ('cash','card','meal_voucher','on_account','comp','other')),
  CONSTRAINT CK_PAY_VOIDED CHECK (IS_VOIDED IN (0,1)),
  CONSTRAINT CK_PAY_AMOUNT CHECK (AMOUNT >= 0)
);
CREATE INDEX IX_PAY_ORDER ON PAYMENTS (ORDER_ID);
CREATE INDEX IX_PAY_TENANT ON PAYMENTS (TENANT_ID, BRANCH_ID);

CREATE TABLE REFUNDS (
  ID          VARCHAR2(36)             NOT NULL,
  TENANT_ID   VARCHAR2(36)             NOT NULL,
  ORDER_ID    VARCHAR2(36)             NOT NULL,
  PAYMENT_ID  VARCHAR2(36),
  AMOUNT      NUMBER(18,4)             NOT NULL,
  REASON      VARCHAR2(300),
  CREATED_BY  VARCHAR2(36),
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_REFUNDS PRIMARY KEY (ID),
  CONSTRAINT FK_REFUND_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID),
  CONSTRAINT CK_REFUND_AMOUNT CHECK (AMOUNT > 0)
);
CREATE INDEX IX_REFUND_ORDER ON REFUNDS (ORDER_ID);

CREATE TABLE INVOICES (
  ID            VARCHAR2(36)             NOT NULL,
  TENANT_ID     VARCHAR2(36)             NOT NULL,
  BRANCH_ID     VARCHAR2(36)             NOT NULL,
  ORDER_ID      VARCHAR2(36)             NOT NULL,
  INVOICE_NO    NUMBER(12)               NOT NULL,
  INVOICE_TYPE  VARCHAR2(20) DEFAULT 'receipt' NOT NULL,
  SUBTOTAL      NUMBER(18,4)             NOT NULL,
  TAX_TOTAL     NUMBER(18,4)             NOT NULL,
  TOTAL         NUMBER(18,4)             NOT NULL,
  CUSTOMER_NAME VARCHAR2(200),
  CUSTOMER_TAX  VARCHAR2(40),
  EXTERNAL_REF  VARCHAR2(120),
  CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_INVOICES PRIMARY KEY (ID),
  CONSTRAINT FK_INV_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID),
  CONSTRAINT UQ_INVOICE_NO UNIQUE (TENANT_ID, INVOICE_NO),
  CONSTRAINT CK_INV_TYPE CHECK (INVOICE_TYPE IN ('receipt','einvoice','earchive'))
);
CREATE INDEX IX_INV_ORDER ON INVOICES (ORDER_ID);

CREATE TABLE CASH_MOVEMENTS (
  ID           VARCHAR2(36)             NOT NULL,
  TENANT_ID    VARCHAR2(36)             NOT NULL,
  BRANCH_ID    VARCHAR2(36)             NOT NULL,
  SESSION_ID   VARCHAR2(36),
  MOVE_TYPE    VARCHAR2(16)             NOT NULL,
  AMOUNT       NUMBER(18,4)             NOT NULL,
  ORDER_ID     VARCHAR2(36),
  PAYMENT_ID   VARCHAR2(36),
  NOTE         VARCHAR2(300),
  CREATED_BY   VARCHAR2(36),
  CREATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_CASH_MOVEMENTS PRIMARY KEY (ID),
  CONSTRAINT CK_CASH_TYPE CHECK (MOVE_TYPE IN ('sale','refund','payin','payout','opening','closing','void'))
);
CREATE INDEX IX_CASH_TENANT ON CASH_MOVEMENTS (TENANT_ID, BRANCH_ID, CREATED_AT);
CREATE INDEX IX_CASH_SESSION ON CASH_MOVEMENTS (SESSION_ID);
