
CREATE TABLE KDS_STATIONS (
  ID          VARCHAR2(36)             NOT NULL,
  TENANT_ID   VARCHAR2(36)             NOT NULL,
  BRANCH_ID   VARCHAR2(36)             NOT NULL,
  NAME        VARCHAR2(120)            NOT NULL,
  CODE        VARCHAR2(40)             NOT NULL,
  SORT_ORDER  NUMBER(6)  DEFAULT 0     NOT NULL,
  IS_ACTIVE   NUMBER(1)  DEFAULT 1     NOT NULL,
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  ROW_VERSION NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_KDS_STATIONS PRIMARY KEY (ID),
  CONSTRAINT FK_KDS_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID),
  CONSTRAINT UQ_KDS_CODE UNIQUE (BRANCH_ID, CODE),
  CONSTRAINT CK_KDS_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);
CREATE INDEX IX_KDS_TENANT ON KDS_STATIONS (TENANT_ID, BRANCH_ID);
