
CREATE TABLE UNITS (
  ID         VARCHAR2(36)  NOT NULL,
  TENANT_ID  VARCHAR2(36)  NOT NULL,
  CODE       VARCHAR2(20)  NOT NULL,
  NAME       VARCHAR2(60)  NOT NULL,
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_UNITS PRIMARY KEY (ID),
  CONSTRAINT UQ_UNITS_CODE UNIQUE (TENANT_ID, CODE)
);

CREATE TABLE STOCK_ITEMS (
  ID            VARCHAR2(36)             NOT NULL,
  TENANT_ID     VARCHAR2(36)             NOT NULL,
  BRANCH_ID     VARCHAR2(36)             NOT NULL,
  NAME          VARCHAR2(200)            NOT NULL,
  SKU           VARCHAR2(60),
  UNIT_ID       VARCHAR2(36)             NOT NULL,
  ON_HAND       NUMBER(18,4) DEFAULT 0   NOT NULL,
  REORDER_LEVEL NUMBER(18,4) DEFAULT 0   NOT NULL,
  UNIT_COST     NUMBER(18,4) DEFAULT 0   NOT NULL,
  IS_ACTIVE     NUMBER(1)  DEFAULT 1     NOT NULL,
  CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY    VARCHAR2(36),
  UPDATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY    VARCHAR2(36),
  ROW_VERSION   NUMBER(19) DEFAULT 1     NOT NULL,
  CONSTRAINT PK_STOCK_ITEMS PRIMARY KEY (ID),
  CONSTRAINT FK_STOCK_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID),
  CONSTRAINT FK_STOCK_UNIT FOREIGN KEY (UNIT_ID) REFERENCES UNITS (ID),
  CONSTRAINT CK_STOCK_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);
CREATE INDEX IX_STOCK_TENANT ON STOCK_ITEMS (TENANT_ID, BRANCH_ID);

CREATE TABLE RECIPES (
  ID           VARCHAR2(36)  NOT NULL,
  TENANT_ID    VARCHAR2(36)  NOT NULL,
  MENU_ITEM_ID VARCHAR2(36)  NOT NULL,
  YIELD_QTY    NUMBER(18,4) DEFAULT 1 NOT NULL,
  CREATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_RECIPES PRIMARY KEY (ID),
  CONSTRAINT FK_RECIPE_ITEM FOREIGN KEY (MENU_ITEM_ID) REFERENCES MENU_ITEMS (ID) ON DELETE CASCADE,
  CONSTRAINT UQ_RECIPE_ITEM UNIQUE (MENU_ITEM_ID)
);

CREATE TABLE RECIPE_LINES (
  ID            VARCHAR2(36)  NOT NULL,
  RECIPE_ID     VARCHAR2(36)  NOT NULL,
  STOCK_ITEM_ID VARCHAR2(36)  NOT NULL,
  QUANTITY      NUMBER(18,4)  NOT NULL,
  CONSTRAINT PK_RECIPE_LINES PRIMARY KEY (ID),
  CONSTRAINT FK_RLINE_RECIPE FOREIGN KEY (RECIPE_ID) REFERENCES RECIPES (ID) ON DELETE CASCADE,
  CONSTRAINT FK_RLINE_STOCK  FOREIGN KEY (STOCK_ITEM_ID) REFERENCES STOCK_ITEMS (ID),
  CONSTRAINT CK_RLINE_QTY CHECK (QUANTITY > 0)
);
CREATE INDEX IX_RLINE_RECIPE ON RECIPE_LINES (RECIPE_ID);

CREATE TABLE STOCK_MOVEMENTS (
  ID            VARCHAR2(36)             NOT NULL,
  TENANT_ID     VARCHAR2(36)             NOT NULL,
  BRANCH_ID     VARCHAR2(36)             NOT NULL,
  STOCK_ITEM_ID VARCHAR2(36)             NOT NULL,
  MOVE_TYPE     VARCHAR2(16)             NOT NULL,
  QUANTITY      NUMBER(18,4)             NOT NULL,
  UNIT_COST     NUMBER(18,4) DEFAULT 0   NOT NULL,
  REF_TYPE      VARCHAR2(20),
  REF_ID        VARCHAR2(36),
  NOTE          VARCHAR2(300),
  CREATED_BY    VARCHAR2(36),
  CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_STOCK_MOVEMENTS PRIMARY KEY (ID),
  CONSTRAINT FK_SMOVE_STOCK FOREIGN KEY (STOCK_ITEM_ID) REFERENCES STOCK_ITEMS (ID),
  CONSTRAINT CK_SMOVE_TYPE CHECK (MOVE_TYPE IN ('purchase','sale','adjustment','wastage','count'))
);
CREATE INDEX IX_SMOVE_ITEM ON STOCK_MOVEMENTS (STOCK_ITEM_ID, CREATED_AT);

CREATE TABLE SUPPLIERS (
  ID         VARCHAR2(36)  NOT NULL,
  TENANT_ID  VARCHAR2(36)  NOT NULL,
  NAME       VARCHAR2(200) NOT NULL,
  PHONE      VARCHAR2(40),
  EMAIL      VARCHAR2(120),
  TAX_NO     VARCHAR2(40),
  IS_ACTIVE  NUMBER(1) DEFAULT 1 NOT NULL,
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_SUPPLIERS PRIMARY KEY (ID),
  CONSTRAINT CK_SUPPLIER_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);
CREATE INDEX IX_SUPPLIER_TENANT ON SUPPLIERS (TENANT_ID);

CREATE TABLE PURCHASE_ORDERS (
  ID          VARCHAR2(36)             NOT NULL,
  TENANT_ID   VARCHAR2(36)             NOT NULL,
  BRANCH_ID   VARCHAR2(36)             NOT NULL,
  SUPPLIER_ID VARCHAR2(36),
  STATUS      VARCHAR2(16) DEFAULT 'draft' NOT NULL,
  TOTAL       NUMBER(18,4) DEFAULT 0   NOT NULL,
  NOTE        VARCHAR2(300),
  CREATED_BY  VARCHAR2(36),
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  RECEIVED_AT TIMESTAMP WITH TIME ZONE,
  CONSTRAINT PK_PURCHASE_ORDERS PRIMARY KEY (ID),
  CONSTRAINT FK_PO_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS (ID),
  CONSTRAINT CK_PO_STATUS CHECK (STATUS IN ('draft','received','cancelled'))
);
CREATE INDEX IX_PO_TENANT ON PURCHASE_ORDERS (TENANT_ID, BRANCH_ID);

CREATE TABLE PURCHASE_LINES (
  ID            VARCHAR2(36)  NOT NULL,
  PURCHASE_ID   VARCHAR2(36)  NOT NULL,
  STOCK_ITEM_ID VARCHAR2(36)  NOT NULL,
  QUANTITY      NUMBER(18,4)  NOT NULL,
  UNIT_COST     NUMBER(18,4)  NOT NULL,
  LINE_TOTAL    NUMBER(18,4)  NOT NULL,
  CONSTRAINT PK_PURCHASE_LINES PRIMARY KEY (ID),
  CONSTRAINT FK_PLINE_PO FOREIGN KEY (PURCHASE_ID) REFERENCES PURCHASE_ORDERS (ID) ON DELETE CASCADE,
  CONSTRAINT FK_PLINE_STOCK FOREIGN KEY (STOCK_ITEM_ID) REFERENCES STOCK_ITEMS (ID),
  CONSTRAINT CK_PLINE_QTY CHECK (QUANTITY > 0)
);
CREATE INDEX IX_PLINE_PO ON PURCHASE_LINES (PURCHASE_ID);

CREATE TABLE WASTAGE (
  ID            VARCHAR2(36)  NOT NULL,
  TENANT_ID     VARCHAR2(36)  NOT NULL,
  BRANCH_ID     VARCHAR2(36)  NOT NULL,
  STOCK_ITEM_ID VARCHAR2(36)  NOT NULL,
  QUANTITY      NUMBER(18,4)  NOT NULL,
  REASON        VARCHAR2(300),
  CREATED_BY    VARCHAR2(36),
  CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_WASTAGE PRIMARY KEY (ID),
  CONSTRAINT FK_WASTE_STOCK FOREIGN KEY (STOCK_ITEM_ID) REFERENCES STOCK_ITEMS (ID),
  CONSTRAINT CK_WASTE_QTY CHECK (QUANTITY > 0)
);
CREATE INDEX IX_WASTE_TENANT ON WASTAGE (TENANT_ID, BRANCH_ID);

CREATE TABLE STOCK_COUNTS (
  ID         VARCHAR2(36)  NOT NULL,
  TENANT_ID  VARCHAR2(36)  NOT NULL,
  BRANCH_ID  VARCHAR2(36)  NOT NULL,
  STATUS     VARCHAR2(16) DEFAULT 'draft' NOT NULL,
  NOTE       VARCHAR2(300),
  CREATED_BY VARCHAR2(36),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  APPLIED_AT TIMESTAMP WITH TIME ZONE,
  CONSTRAINT PK_STOCK_COUNTS PRIMARY KEY (ID),
  CONSTRAINT CK_COUNT_STATUS CHECK (STATUS IN ('draft','applied'))
);

CREATE TABLE STOCK_COUNT_LINES (
  ID            VARCHAR2(36)  NOT NULL,
  COUNT_ID      VARCHAR2(36)  NOT NULL,
  STOCK_ITEM_ID VARCHAR2(36)  NOT NULL,
  COUNTED_QTY   NUMBER(18,4)  NOT NULL,
  SYSTEM_QTY    NUMBER(18,4)  NOT NULL,
  CONSTRAINT PK_STOCK_COUNT_LINES PRIMARY KEY (ID),
  CONSTRAINT FK_CLINE_COUNT FOREIGN KEY (COUNT_ID) REFERENCES STOCK_COUNTS (ID) ON DELETE CASCADE,
  CONSTRAINT FK_CLINE_STOCK FOREIGN KEY (STOCK_ITEM_ID) REFERENCES STOCK_ITEMS (ID)
);
CREATE INDEX IX_CLINE_COUNT ON STOCK_COUNT_LINES (COUNT_ID);
